from __future__ import annotations

try:  # pragma: no cover - package import path
    import troTHU.runtime_context as ctx
except ImportError:  # pragma: no cover - direct script fallback
    import runtime_context as ctx  # type: ignore


def __getattr__(name: str):
    return getattr(ctx, name)



def build_arg_parser() -> ctx.argparse.ArgumentParser:
    parser = ctx.argparse.ArgumentParser(description='THU TronClass auto rollcall helper')
    subcommands = parser.add_subparsers(dest='command')
    run_parser = subcommands.add_parser('run', help='啟動無 UI 監控 console')
    run_mode = run_parser.add_mutually_exclusive_group()
    run_mode.add_argument('--classic', action='store_true', help='相容舊參數；仍使用新版單視窗監控輸出')
    run_mode.add_argument('--no-input', action='store_true', help='只輸出監控事件，不監聽任意鍵開啟 config.yaml')
    init_parser = subcommands.add_parser('init', help='run first-time setup wizard')
    init_parser.add_argument('--profile', default='', help='profile name to create or update')
    init_parser.add_argument('--user', default='', help='student id')
    init_parser.add_argument('--password', default='', help='password; omit to prompt securely')
    init_parser.add_argument('--store', choices=('keyring', 'env', 'config', 'none'), default='keyring', help='where to store the password')
    init_parser.add_argument('--label', default='', help='optional display label')
    init_parser.add_argument('--telegram-token', default='', help='Telegram bot token')
    init_parser.add_argument('--telegram-chat', default='', help='Telegram chat id')
    init_parser.add_argument('--discord-token', default='', help='Discord bot token')
    init_parser.add_argument('--discord-chat', default='', help='Discord channel id')
    init_parser.add_argument('--test-login', action='store_true', help='verify login without checking rollcalls')
    init_parser.add_argument('--dry-run', action='store_true', help='show planned changes without saving')
    init_parser.add_argument('--yes', action='store_true', help='accept defaults for omitted interactive answers')
    init_parser.add_argument('--json', action='store_true', help='print machine-readable output')
    status_parser = subcommands.add_parser('status', help='show local configuration status')
    status_parser.add_argument('--json', action='store_true', help='print JSON')
    doctor_parser = subcommands.add_parser('doctor', help='run local non-network diagnostics')
    doctor_parser.add_argument('--json', action='store_true', help='print JSON')
    config_parser = subcommands.add_parser('config', help='查看與整理人性化 config.yaml')
    config_subcommands = config_parser.add_subparsers(dest='config_command')
    config_show = config_subcommands.add_parser('show', help='顯示精簡設定摘要')
    config_show.add_argument('--json', action='store_true', help='print JSON')
    config_compact = config_subcommands.add_parser('compact', help='將 config.yaml 整理成精簡格式')
    compact_mode = config_compact.add_mutually_exclusive_group()
    compact_mode.add_argument('--dry-run', action='store_true', help='只預覽，不寫入')
    compact_mode.add_argument('--write', action='store_true', help='備份後寫入精簡格式')
    config_compact.add_argument('--json', action='store_true', help='print JSON')
    config_doctor = config_subcommands.add_parser('doctor', help='檢查 config.yaml 常見輸入問題')
    config_doctor.add_argument('--json', action='store_true', help='print JSON')
    config_advanced = config_subcommands.add_parser('advanced', help='用舊版記事本開啟 config.advanced.yaml')
    config_advanced.add_argument('--json', action='store_true', help='print JSON')
    package_check_parser = subcommands.add_parser('package-check', help='run packaging and bundle diagnostics')
    package_check_parser.add_argument('--json', action='store_true', help='print JSON')
    release_check_parser = subcommands.add_parser('release-check', help='run release readiness checks')
    release_check_parser.add_argument('--dist', default='', help='optional dist artifact or directory to inspect')
    release_check_parser.add_argument('--plan', action='store_true', help='include non-executing release build plan')
    release_check_parser.add_argument('--json', action='store_true', help='print JSON')
    release_build_parser = subcommands.add_parser('release-build', help='run safe local release build pipeline')
    release_build_mode = release_build_parser.add_mutually_exclusive_group()
    release_build_mode.add_argument('--dry-run', action='store_true', help='print release build plan without building')
    release_build_mode.add_argument('--execute', action='store_true', help='run tests, PyInstaller, zip packaging, and smoke')
    release_build_parser.add_argument('--dist', default='', help='dist directory for artifact output')
    release_build_parser.add_argument('--work', default='', help='work directory for build and smoke temp files')
    release_build_parser.add_argument('--json', action='store_true', help='print JSON')
    roadmap_parser = subcommands.add_parser('roadmap', help='inspect distance to upper replacement goal')
    roadmap_subcommands = roadmap_parser.add_subparsers(dest='roadmap_command')
    roadmap_audit = roadmap_subcommands.add_parser('audit', help='print strategic distance audit')
    roadmap_audit.add_argument('--json', action='store_true', help='print JSON')
    roadmap_rounds = roadmap_subcommands.add_parser('rounds', help='print remaining engineering round plan')
    roadmap_rounds.add_argument('--json', action='store_true', help='print JSON')
    validation_parser = subcommands.add_parser('validation', help='record R1 real validation acceptance')
    validation_subcommands = validation_parser.add_subparsers(dest='validation_command')
    validation_checklist = validation_subcommands.add_parser('checklist', help='print R1 validation checklist')
    validation_checklist.add_argument('--json', action='store_true', help='print JSON')
    validation_record = validation_subcommands.add_parser('record', help='append one sanitized validation result')
    validation_record.add_argument('case', help='validation case id')
    validation_record.add_argument('--status', choices=('pass', 'fail', 'blocked', 'skip'), required=True)
    validation_record.add_argument('--note', default='', help='short sanitized note')
    validation_record.add_argument('--reason', default='', help='safe reason, e.g. blocked_by_no_live_rollcall')
    validation_record.add_argument('--profile', default='', help='profile name; defaults to active')
    validation_record.add_argument('--provider', default='', help='provider key; defaults to active')
    validation_record.add_argument('--json', action='store_true', help='print JSON')
    validation_summary = validation_subcommands.add_parser('summary', help='summarize R1 validation records')
    validation_summary.add_argument('--json', action='store_true', help='print JSON')
    validation_local_smoke = validation_subcommands.add_parser('local-smoke', help='run local/offline R1 smoke checks')
    validation_local_smoke.add_argument('--json', action='store_true', help='print JSON')
    provider_parser = subcommands.add_parser('provider', help='inspect TronClass provider support')
    provider_subcommands = provider_parser.add_subparsers(dest='provider_command')
    provider_list = provider_subcommands.add_parser('list', help='list supported providers')
    provider_list.add_argument('--json', action='store_true', help='print JSON')
    provider_show = provider_subcommands.add_parser('show', help='show one provider')
    provider_show.add_argument('name', nargs='?', default='', help='provider key; defaults to active')
    provider_show.add_argument('--json', action='store_true', help='print JSON')
    provider_verify = provider_subcommands.add_parser('verify-checklist', help='print provider manual verification checklist')
    provider_verify.add_argument('name', nargs='?', default='', help='provider key; defaults to active')
    provider_verify.add_argument('--json', action='store_true', help='print JSON')
    provider_ready = provider_subcommands.add_parser('ready-gate', help='evaluate provider ready gate')
    provider_ready.add_argument('name', nargs='?', default='', help='provider key; defaults to active')
    provider_ready.add_argument('--fixture', default='', help='sanitized fixture JSON path')
    provider_ready.add_argument('--json', action='store_true', help='print JSON')
    provider_fixture = provider_subcommands.add_parser('fixture', help='work with sanitized provider fixtures')
    provider_fixture_subcommands = provider_fixture.add_subparsers(dest='provider_fixture_command')
    provider_fixture_template = provider_fixture_subcommands.add_parser('template', help='print a sanitized fixture template')
    provider_fixture_template.add_argument('name', nargs='?', default='', help='provider key; defaults to active')
    provider_fixture_template.add_argument('--json', action='store_true', help='print JSON')
    provider_fixture_validate = provider_fixture_subcommands.add_parser('validate', help='validate a sanitized fixture')
    provider_fixture_validate.add_argument('--input', required=True, help='fixture JSON path')
    provider_fixture_validate.add_argument('--provider', default='', help='expected provider key')
    provider_fixture_validate.add_argument('--json', action='store_true', help='print JSON')
    provider_fixture_review_template = provider_fixture_subcommands.add_parser('review-template', help='print a fixture review template')
    provider_fixture_review_template.add_argument('name', nargs='?', default='', help='provider key; defaults to active')
    provider_fixture_review_template.add_argument('--json', action='store_true', help='print JSON')
    provider_fixture_review = provider_fixture_subcommands.add_parser('review', help='review one sanitized fixture')
    provider_fixture_review.add_argument('--input', required=True, help='fixture JSON path')
    provider_fixture_review.add_argument('--provider', default='', help='expected provider key')
    provider_fixture_review.add_argument('--json', action='store_true', help='print JSON')
    provider_fixture_review_dir = provider_fixture_subcommands.add_parser('review-dir', help='review all fixture JSON files in a directory')
    provider_fixture_review_dir.add_argument('--dir', required=True, help='fixture directory')
    provider_fixture_review_dir.add_argument('--json', action='store_true', help='print JSON')
    app_parser = subcommands.add_parser('app', help='inspect future App/GUI architecture contracts')
    app_subcommands = app_parser.add_subparsers(dest='app_command')
    app_blueprint = app_subcommands.add_parser('blueprint', help='print future App/GUI blueprint')
    app_blueprint.add_argument('--json', action='store_true', help='print JSON')
    app_serve = app_subcommands.add_parser('serve', help='start optional localhost companion shell')
    app_serve.add_argument('--host', default='127.0.0.1', help='host to bind; defaults to localhost')
    app_serve.add_argument('--port', type=int, default=8790, help='port to bind')
    app_serve.add_argument('--open', action='store_true', help='open the local shell in the default browser')
    app_serve.add_argument('--ttl-seconds', type=int, default=900, help='local token lifetime')
    app_serve.add_argument('--json', action='store_true', help='print startup metadata as JSON')
    webview_parser = subcommands.add_parser('webview', help='inspect or import WebView login cookies')
    webview_subcommands = webview_parser.add_subparsers(dest='webview_command')
    webview_status = webview_subcommands.add_parser('status', help='show WebView cookie sync gates')
    webview_status.add_argument('--json', action='store_true', help='print JSON')
    webview_preview = webview_subcommands.add_parser('preview', help='preview a WebView cookie export')
    webview_preview.add_argument('--input', required=True, help='JSON cookie export path')
    webview_preview.add_argument('--profile', default='', help='profile name; defaults to active')
    webview_preview.add_argument('--json', action='store_true', help='print JSON')
    webview_import = webview_subcommands.add_parser('import', help='import accepted cookies into cookie cache')
    webview_import.add_argument('--input', required=True, help='JSON cookie export path')
    webview_import.add_argument('--profile', default='', help='profile name; defaults to active')
    webview_import.add_argument('--save', action='store_true', help='write accepted cookies to local cookie cache')
    webview_import.add_argument('--json', action='store_true', help='print JSON')
    courses_parser = subcommands.add_parser('courses', help='discover current semester and courses')
    courses_parser.add_argument('--json', action='store_true', help='print JSON')
    subcommands.add_parser('refresh', help='delete cached cookies for the active profile')
    dashboard_parser = subcommands.add_parser('dashboard', help='show a lightweight terminal dashboard')
    dashboard_parser.add_argument('--once', action='store_true', help='render once and exit')
    dashboard_parser.add_argument('--interval', type=float, default=2.0, help='refresh interval seconds')
    dashboard_parser.add_argument('--json', action='store_true', help='print one machine-readable snapshot')
    debug_parser = subcommands.add_parser('debug-capture', help='capture one sanitized rollcall API snapshot for diagnostics')
    debug_parser.add_argument('--output', default='', help='JSONL output path; defaults to state/debug-capture/rollcalls.jsonl')
    research_parser = subcommands.add_parser('research', help='run opt-in research diagnostics')
    research_subcommands = research_parser.add_subparsers(dest='research_command')
    research_status = research_subcommands.add_parser('status', help='show research mode gates')
    research_status.add_argument('--json', action='store_true', help='print JSON')
    research_api = research_subcommands.add_parser('api', help='capture sanitized read-only API metadata')
    research_api.add_argument('--target', default='all', help='safe target: home, rollcalls, semester, courses, or all')
    research_api.add_argument('--output', default='', help='optional JSONL output path')
    research_api.add_argument('--json', action='store_true', help='print JSON')
    research_browser_check = research_subcommands.add_parser('browser-check', help='check optional Playwright availability')
    research_browser_check.add_argument('--json', action='store_true', help='print JSON')
    research_browser_capture = research_subcommands.add_parser('browser-capture', help='capture sanitized browser request metadata without logging in')
    research_browser_capture.add_argument('--target', choices=('login', 'home'), default='home')
    research_browser_capture.add_argument('--json', action='store_true', help='print JSON')
    qr_parser = subcommands.add_parser('qr', help='submit, preview, or scan TronClass QR payloads')
    qr_parser.add_argument('qr_args', nargs='*', help='payload, or subcommands: paste/pending/scan')
    qr_parser.add_argument('--yes', action='store_true', help='skip QR paste confirmation')
    qr_parser.add_argument('--all', dest='fanout_all', action='store_true', help='submit to all matching pending profiles')
    qr_parser.add_argument('--json', action='store_true', help='print JSON for preview/pending')
    qr_parser.add_argument('--host', default='', help='local scanner host')
    qr_parser.add_argument('--port', type=int, default=0, help='local scanner port')
    qr_parser.add_argument('--open', action='store_true', help='open local scanner in browser')
    logs_parser = subcommands.add_parser('logs', help='inspect sanitized local logs')
    logs_subcommands = logs_parser.add_subparsers(dest='logs_command')
    logs_tail = logs_subcommands.add_parser('tail', help='print recent JSONL log records')
    logs_tail.add_argument('--limit', type=int, default=20)
    logs_tail.add_argument('--json', action='store_true')
    logs_summary = logs_subcommands.add_parser('summarize', help='summarize log records')
    logs_summary.add_argument('--limit', type=int, default=20, help='recent records to include in notable event summary')
    logs_summary.add_argument('--json', action='store_true')
    logs_summary_alias = logs_subcommands.add_parser('summary', help='alias for summarize')
    logs_summary_alias.add_argument('--limit', type=int, default=20, help='recent records to include in notable event summary')
    logs_summary_alias.add_argument('--json', action='store_true')
    logs_export = logs_subcommands.add_parser('export', help='write a redacted debug bundle')
    logs_export.add_argument('--output', default='', help='output zip path')
    logs_export.add_argument('--json', action='store_true')
    logs_export.add_argument('--limit', type=int, default=50)
    account_parser = subcommands.add_parser('account', help='manage account profiles')
    account_subcommands = account_parser.add_subparsers(dest='account_command')
    account_list = account_subcommands.add_parser('list', help='list account profiles')
    account_list.add_argument('--json', action='store_true')
    account_show_parser = account_subcommands.add_parser('show', help='show one account profile')
    account_show_parser.add_argument('name', nargs='?', default='', help='profile name; defaults to active')
    account_show_parser.add_argument('--json', action='store_true')
    account_state_parser = account_subcommands.add_parser('state', help='show runtime state for one account profile')
    account_state_parser.add_argument('name', nargs='?', default='', help='profile name; defaults to active')
    account_state_parser.add_argument('--json', action='store_true')
    account_doctor_parser = account_subcommands.add_parser('doctor', help='diagnose one account profile')
    account_doctor_parser.add_argument('name', nargs='?', default='', help='profile name; defaults to active')
    account_doctor_parser.add_argument('--json', action='store_true')
    account_add = account_subcommands.add_parser('add', help='add or update an account profile')
    account_add.add_argument('name', help='profile name')
    account_add.add_argument('--user', help='student id')
    account_add.add_argument('--password', help='password; omit to prompt securely')
    account_add.add_argument('--store', choices=('keyring', 'env', 'config', 'none'), default='keyring', help='where to store the password')
    account_add.add_argument('--label', default='', help='optional display label')
    account_add.add_argument('--no-switch', action='store_true', help='do not switch to this profile')
    account_switch = account_subcommands.add_parser('switch', help='switch active profile')
    account_switch.add_argument('name', help='profile name')
    account_remove = account_subcommands.add_parser('remove', help='remove an account profile')
    account_remove.add_argument('name', help='profile name')
    account_bind = account_subcommands.add_parser('bind', help='bind adapter user id to a profile')
    account_bind.add_argument('adapter', choices=('discord', 'line', 'telegram'))
    account_bind.add_argument('external_user_id')
    account_bind.add_argument('profile')
    account_bind.add_argument('--channel', default='')
    account_unbind = account_subcommands.add_parser('unbind', help='remove adapter binding')
    account_unbind.add_argument('adapter', choices=('discord', 'line', 'telegram'))
    account_unbind.add_argument('external_user_id')
    bot_parser = subcommands.add_parser('bot', help='run bot adapter services')
    bot_subcommands = bot_parser.add_subparsers(dest='bot_command')
    bot_serve = bot_subcommands.add_parser('serve', help='serve bot adapter webhooks')
    bot_serve.add_argument('--host', default='127.0.0.1', help='bind host')
    bot_serve.add_argument('--port', type=int, default=8787, help='bind port')
    bot_serve.add_argument('--adapter', choices=('all', 'generic', 'line', 'discord'), default='all')
    bot_serve.add_argument('--json', action='store_true', help='print startup metadata as JSON')
    bot_schema = bot_subcommands.add_parser('discord-schema', help='print Discord slash command schema')
    bot_schema.add_argument('--json', action='store_true', help='print schema as JSON')
    bot_discord_sync = bot_subcommands.add_parser('discord-sync', help='sync Discord slash command schema')
    bot_discord_sync.add_argument('--apply', action='store_true', help='apply schema to Discord; default is dry-run')
    bot_discord_sync.add_argument('--dry-run', action='store_true', help='show planned sync without network')
    bot_discord_sync.add_argument('--json', action='store_true', help='print JSON')
    bot_discord_gateway = bot_subcommands.add_parser('discord-gateway', help='run optional Discord Gateway')
    bot_discord_gateway.add_argument('--dry-run', action='store_true', help='print safe health without connecting')
    bot_discord_gateway.add_argument('--json', action='store_true', help='print JSON')
    return parser
