from __future__ import annotations

try:  # pragma: no cover - package import path
    import troTHU.runtime_context as ctx
except ImportError:  # pragma: no cover - direct script fallback
    import runtime_context as ctx  # type: ignore


def __getattr__(name: str):
    return getattr(ctx, name)



def build_arg_parser() -> ctx.argparse.ArgumentParser:
    parser = ctx.argparse.ArgumentParser(description='THU TronClass auto rollcall helper')
    subcommands = parser.add_subparsers(dest='command')
    run_parser = subcommands.add_parser('run', help='啟動無 UI 監控 console')
    run_mode = run_parser.add_mutually_exclusive_group()
    run_mode.add_argument('--classic', action='store_true', help='相容舊參數；仍使用新版單視窗監控輸出')
    run_mode.add_argument('--no-input', action='store_true', help='只輸出監控事件，不監聽任意鍵開啟 config.yaml')
    init_parser = subcommands.add_parser('init', help='run first-time setup wizard')
    init_parser.add_argument('--profile', default='', help='profile name to create or update')
    init_parser.add_argument('--user', default='', help='student id')
    init_parser.add_argument('--password', default='', help='password; omit to prompt securely')
    init_parser.add_argument('--store', choices=('keyring', 'env', 'config', 'none'), default='keyring', help='where to store the password')
    init_parser.add_argument('--label', default='', help='optional display label')
    init_parser.add_argument('--telegram-token', default='', help='Telegram bot token')
    init_parser.add_argument('--telegram-chat', default='', help='Telegram chat id')
    init_parser.add_argument('--discord-token', default='', help='Discord bot token')
    init_parser.add_argument('--discord-chat', default='', help='Discord channel id')
    init_parser.add_argument('--test-login', action='store_true', help='verify login without checking rollcalls')
    init_parser.add_argument('--dry-run', action='store_true', help='show planned changes without saving')
    init_parser.add_argument('--yes', action='store_true', help='accept defaults for omitted interactive answers')
    init_parser.add_argument('--json', action='store_true', help='print machine-readable output')
    status_parser = subcommands.add_parser('status', help='show local configuration status')
    status_parser.add_argument('--json', action='store_true', help='print JSON')
    doctor_parser = subcommands.add_parser('doctor', help='run local non-network diagnostics')
    doctor_parser.add_argument('--json', action='store_true', help='print JSON')
    doctor_parser.add_argument('--probe-url', default='', help='optional HTTP URL to probe; off by default')
    doctor_parser.add_argument('--probe-count', type=int, default=3, help='optional probe attempt count')
    doctor_parser.add_argument('--probe-concurrency', type=int, default=1, help='optional probe concurrency')
    config_parser = subcommands.add_parser('config', help='查看與整理人性化 config.yaml')
    config_subcommands = config_parser.add_subparsers(dest='config_command')
    config_show = config_subcommands.add_parser('show', help='顯示精簡設定摘要')
    config_show.add_argument('--json', action='store_true', help='print JSON')
    config_compact = config_subcommands.add_parser('compact', help='將 config.yaml 整理成精簡格式')
    compact_mode = config_compact.add_mutually_exclusive_group()
    compact_mode.add_argument('--dry-run', action='store_true', help='只預覽，不寫入')
    compact_mode.add_argument('--write', action='store_true', help='備份後寫入精簡格式')
    config_compact.add_argument('--json', action='store_true', help='print JSON')
    config_doctor = config_subcommands.add_parser('doctor', help='檢查 config.yaml 常見輸入問題')
    config_doctor.add_argument('--json', action='store_true', help='print JSON')
    config_advanced = config_subcommands.add_parser('advanced', help='用舊版記事本開啟 config.advanced.yaml')
    config_advanced.add_argument('--json', action='store_true', help='print JSON')
    package_check_parser = subcommands.add_parser('package-check', help='run packaging and bundle diagnostics')
    package_check_parser.add_argument('--json', action='store_true', help='print JSON')
    release_check_parser = subcommands.add_parser('release-check', help='run release readiness checks')
    release_check_parser.add_argument('--dist', default='', help='optional dist artifact or directory to inspect')
    release_check_parser.add_argument('--plan', action='store_true', help='include non-executing release build plan')
    release_check_parser.add_argument('--json', action='store_true', help='print JSON')
    release_build_parser = subcommands.add_parser('release-build', help='run safe local release build pipeline')
    release_build_mode = release_build_parser.add_mutually_exclusive_group()
    release_build_mode.add_argument('--dry-run', action='store_true', help='print release build plan without building')
    release_build_mode.add_argument('--execute', action='store_true', help='run tests, PyInstaller, zip packaging, and smoke')
    release_build_parser.add_argument('--dist', default='', help='dist directory for artifact output')
    release_build_parser.add_argument('--work', default='', help='work directory for build and smoke temp files')
    release_build_parser.add_argument('--json', action='store_true', help='print JSON')
    validation_parser = subcommands.add_parser('validation', help='record R1 real validation acceptance')
    validation_subcommands = validation_parser.add_subparsers(dest='validation_command')
    validation_checklist = validation_subcommands.add_parser('checklist', help='print R1 validation checklist')
    validation_checklist.add_argument('--json', action='store_true', help='print JSON')
    validation_record = validation_subcommands.add_parser('record', help='append one sanitized validation result')
    validation_record.add_argument('case', help='validation case id')
    validation_record.add_argument('--status', choices=('pass', 'fail', 'blocked', 'skip'), required=True)
    validation_record.add_argument('--note', default='', help='short sanitized note')
    validation_record.add_argument('--reason', default='', help='safe reason, e.g. blocked_by_no_live_rollcall')
    validation_record.add_argument('--profile', default='', help='profile name; defaults to active')
    validation_record.add_argument('--provider', default='', help='provider key; defaults to active')
    validation_record.add_argument('--json', action='store_true', help='print JSON')
    validation_summary = validation_subcommands.add_parser('summary', help='summarize R1 validation records')
    validation_summary.add_argument('--json', action='store_true', help='print JSON')
    validation_local_smoke = validation_subcommands.add_parser('local-smoke', help='run local/offline R1 smoke checks')
    validation_local_smoke.add_argument('--json', action='store_true', help='print JSON')
    validation_local_smoke.add_argument('--record', action='store_true', help='append pass/fail records for offline-proven validation cases')
    provider_parser = subcommands.add_parser('provider', help='inspect TronClass provider support')
    provider_subcommands = provider_parser.add_subparsers(dest='provider_command')
    provider_list = provider_subcommands.add_parser('list', help='list supported providers')
    provider_list.add_argument('--json', action='store_true', help='print JSON')
    provider_list.add_argument('--all', action='store_true', help='include hidden/internal providers')
    provider_show = provider_subcommands.add_parser('show', help='show one provider')
    provider_show.add_argument('name', nargs='?', default='', help='provider key; defaults to active')
    provider_show.add_argument('--json', action='store_true', help='print JSON')
    provider_verify = provider_subcommands.add_parser('verify-checklist', help='print provider manual verification checklist')
    provider_verify.add_argument('name', nargs='?', default='', help='provider key; defaults to active')
    provider_verify.add_argument('--json', action='store_true', help='print JSON')
    provider_ready = provider_subcommands.add_parser('ready-gate', help='evaluate provider ready gate')
    provider_ready.add_argument('name', nargs='?', default='', help='provider key; defaults to active')
    provider_ready.add_argument('--fixture', default='', help='sanitized fixture JSON path')
    provider_ready.add_argument('--json', action='store_true', help='print JSON')
    provider_fixture = provider_subcommands.add_parser('fixture', help='work with sanitized provider fixtures')
    provider_fixture_subcommands = provider_fixture.add_subparsers(dest='provider_fixture_command')
    provider_fixture_template = provider_fixture_subcommands.add_parser('template', help='print a sanitized fixture template')
    provider_fixture_template.add_argument('name', nargs='?', default='', help='provider key; defaults to active')
    provider_fixture_template.add_argument('--json', action='store_true', help='print JSON')
    provider_fixture_validate = provider_fixture_subcommands.add_parser('validate', help='validate a sanitized fixture')
    provider_fixture_validate.add_argument('--input', required=True, help='fixture JSON path')
    provider_fixture_validate.add_argument('--provider', default='', help='expected provider key')
    provider_fixture_validate.add_argument('--json', action='store_true', help='print JSON')
    provider_fixture_review_template = provider_fixture_subcommands.add_parser('review-template', help='print a fixture review template')
    provider_fixture_review_template.add_argument('name', nargs='?', default='', help='provider key; defaults to active')
    provider_fixture_review_template.add_argument('--json', action='store_true', help='print JSON')
    provider_fixture_review = provider_fixture_subcommands.add_parser('review', help='review one sanitized fixture')
    provider_fixture_review.add_argument('--input', required=True, help='fixture JSON path')
    provider_fixture_review.add_argument('--provider', default='', help='expected provider key')
    provider_fixture_review.add_argument('--json', action='store_true', help='print JSON')
    provider_fixture_review_dir = provider_fixture_subcommands.add_parser('review-dir', help='review all fixture JSON files in a directory')
    provider_fixture_review_dir.add_argument('--dir', required=True, help='fixture directory')
    provider_fixture_review_dir.add_argument('--json', action='store_true', help='print JSON')
    app_parser = subcommands.add_parser('app', help='inspect future App/GUI architecture contracts')
    app_subcommands = app_parser.add_subparsers(dest='app_command')
    app_blueprint = app_subcommands.add_parser('blueprint', help='print future App/GUI blueprint')
    app_blueprint.add_argument('--json', action='store_true', help='print JSON')
    app_serve = app_subcommands.add_parser('serve', help='start optional localhost companion shell')
    app_serve.add_argument('--host', default='127.0.0.1', help='host to bind; defaults to localhost')
    app_serve.add_argument('--port', type=int, default=8790, help='port to bind')
    app_serve.add_argument('--open', action='store_true', help='open the local shell in the default browser')
    app_serve.add_argument('--ttl-seconds', type=int, default=900, help='local token lifetime')
    app_serve.add_argument('--json', action='store_true', help='print startup metadata as JSON')
    webview_parser = subcommands.add_parser('webview', help='inspect or import WebView login cookies')
    webview_subcommands = webview_parser.add_subparsers(dest='webview_command')
    webview_status = webview_subcommands.add_parser('status', help='show WebView cookie sync gates')
    webview_status.add_argument('--json', action='store_true', help='print JSON')
    webview_preview = webview_subcommands.add_parser('preview', help='preview a WebView cookie export')
    webview_preview.add_argument('--input', required=True, help='JSON cookie export path')
    webview_preview.add_argument('--profile', default='', help='profile name; defaults to active')
    webview_preview.add_argument('--json', action='store_true', help='print JSON')
    webview_import = webview_subcommands.add_parser('import', help='import accepted cookies into cookie cache')
    webview_import.add_argument('--input', required=True, help='JSON cookie export path')
    webview_import.add_argument('--profile', default='', help='profile name; defaults to active')
    webview_import.add_argument('--save', action='store_true', help='write accepted cookies to local cookie cache')
    webview_import.add_argument('--json', action='store_true', help='print JSON')
    courses_parser = subcommands.add_parser('courses', help='discover current semester and courses')
    courses_parser.add_argument('--json', action='store_true', help='print JSON')
    teacher_parser = subcommands.add_parser('teacher', help='teacher-side rollcall tools')
    teacher_subcommands = teacher_parser.add_subparsers(dest='teacher_command')
    teacher_status = teacher_subcommands.add_parser('status', help='detect teacher-capable courses for the active account')
    teacher_status.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall = teacher_subcommands.add_parser('rollcall', help='create and manage teacher rollcalls')
    teacher_rollcall_subcommands = teacher_rollcall.add_subparsers(dest='teacher_rollcall_command')
    teacher_rollcall_list = teacher_rollcall_subcommands.add_parser('list', help='list rollcalls in a teacher course')
    teacher_rollcall_list.add_argument('--course-id', required=True, help='course id')
    teacher_rollcall_list.add_argument('--force', action='store_true', help='skip local teacher role gate and let the server decide')
    teacher_rollcall_list.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_root = teacher_rollcall_subcommands.add_parser('root', help='raw /api/rollcall/ root request')
    teacher_rollcall_root.add_argument('--method', choices=('GET', 'POST', 'PUT', 'DELETE'), default='GET')
    teacher_rollcall_root.add_argument('--params-json', default='', help='optional JSON object query params')
    teacher_rollcall_root.add_argument('--payload-json', default='', help='JSON object payload for POST/PUT/DELETE')
    teacher_rollcall_root.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_status_list = teacher_rollcall_subcommands.add_parser('status-list', help='show rollcall status list')
    teacher_rollcall_status_list.add_argument('--params-json', default='', help='optional JSON object query params')
    teacher_rollcall_status_list.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_summary = teacher_rollcall_subcommands.add_parser('summary', help='show course rollcall list, settings, scores, and timetable rows')
    teacher_rollcall_summary.add_argument('--course-id', required=True, help='course id')
    teacher_rollcall_summary.add_argument('--page-size', type=int, default=20, help='sample size for course rollcall student pages')
    teacher_rollcall_summary.add_argument('--force', action='store_true', help='skip local teacher role gate and let the server decide')
    teacher_rollcall_summary.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_roster = teacher_rollcall_subcommands.add_parser('roster', help='show the course student roster')
    teacher_rollcall_roster.add_argument('--course-id', required=True, help='course id')
    teacher_rollcall_roster.add_argument('--force', action='store_true', help='skip local teacher role gate and let the server decide')
    teacher_rollcall_roster.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_stats = teacher_rollcall_subcommands.add_parser('stats', help='show course rollcall statistics')
    teacher_rollcall_stats.add_argument('--course-id', required=True, help='course id')
    teacher_rollcall_stats.add_argument('--force', action='store_true', help='skip local teacher role gate and let the server decide')
    teacher_rollcall_stats.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_detail = teacher_rollcall_subcommands.add_parser('detail', help='show one course rollcall detail')
    teacher_rollcall_detail.add_argument('--course-id', required=True, help='course id')
    teacher_rollcall_detail.add_argument('rollcall_id')
    teacher_rollcall_detail.add_argument('--force', action='store_true', help='skip local teacher role gate and let the server decide')
    teacher_rollcall_detail.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_onprogress = teacher_rollcall_subcommands.add_parser('onprogress', help='show current student-visible rollcalls in a course')
    teacher_rollcall_onprogress.add_argument('--course-id', required=True, help='course id')
    teacher_rollcall_onprogress.add_argument('--group-rollcall', default='', help='optional group_rollcall query value')
    teacher_rollcall_onprogress.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_leave = teacher_rollcall_subcommands.add_parser('leave-record', help='show course leave records')
    teacher_rollcall_leave.add_argument('--course-id', required=True, help='course id')
    teacher_rollcall_leave.add_argument('--timestamp', default='', help='optional timestamp cursor')
    teacher_rollcall_leave.add_argument('--page', type=int, default=None, help='optional page')
    teacher_rollcall_leave.add_argument('--page-size', type=int, default=None, help='optional page size')
    teacher_rollcall_leave.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_create = teacher_rollcall_subcommands.add_parser('create', help='create a teacher rollcall')
    teacher_rollcall_create.add_argument('--course-id', required=True, help='course id')
    teacher_rollcall_create.add_argument('--type', choices=('manual', 'number', 'radar', 'qr', 'self_registration', 'self-registration'), default='manual', help='rollcall type')
    teacher_rollcall_create.add_argument('--title', default='', help='rollcall title; defaults to current local minute')
    teacher_rollcall_create.add_argument('--activity-status', default='', help='rollcall status sent to the server, e.g. waiting or in_progress')
    teacher_rollcall_create.add_argument('--number-code', default='', help='number rollcall code; defaults to a random four-digit code')
    teacher_rollcall_create.add_argument('--latitude', type=float, default=None, help='radar latitude')
    teacher_rollcall_create.add_argument('--longitude', type=float, default=None, help='radar longitude')
    teacher_rollcall_create.add_argument('--altitude', type=float, default=None, help='radar altitude')
    teacher_rollcall_create.add_argument('--use-beacon', action='store_true', help='enable beacon flag when supported')
    teacher_rollcall_create.add_argument('--duration-seconds', type=int, default=0, help='optional duration in seconds')
    teacher_rollcall_create.add_argument('--duration-min', type=int, default=0, help='optional duration in minutes')
    teacher_rollcall_create.add_argument('--default-status', default='', help='default student status, e.g. absent')
    teacher_rollcall_create.add_argument('--input', default='', help='JSON list/path for initial student_rollcalls')
    teacher_rollcall_create.add_argument('--payload-json', default='', help='raw JSON payload; when set, type-specific flags are ignored')
    teacher_rollcall_create.add_argument('--start', action='store_true', help='start after creating')
    teacher_rollcall_create.add_argument('--force', action='store_true', help='skip local teacher role gate and let the server decide')
    teacher_rollcall_create.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_module_create = teacher_rollcall_subcommands.add_parser('module-create', help='create a rollcall from a module activity')
    teacher_rollcall_module_create.add_argument('--course-id', required=True, help='course id')
    teacher_rollcall_module_create.add_argument('--module-id', required=True, help='module id')
    teacher_rollcall_module_create.add_argument('--title', default='', help='rollcall title; defaults to current local minute')
    teacher_rollcall_module_create.add_argument('--type', choices=('manual', 'number', 'radar', 'qr', 'self_registration', 'self-registration'), default='qr', help='rollcall type')
    teacher_rollcall_module_create.add_argument('--activity-status', default='waiting', help='rollcall status sent to the server')
    teacher_rollcall_module_create.add_argument('--payload-json', default='', help='raw JSON payload; when set, type-specific flags are ignored')
    teacher_rollcall_module_create.add_argument('--force', action='store_true', help='skip local teacher role gate and let the server decide')
    teacher_rollcall_module_create.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_start = teacher_rollcall_subcommands.add_parser('start', help='start a rollcall')
    teacher_rollcall_start.add_argument('rollcall_id')
    teacher_rollcall_start.add_argument('--payload-json', default='', help='optional JSON payload for start-rollcall')
    teacher_rollcall_start.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_activate = teacher_rollcall_subcommands.add_parser('activate', help='keep a rollcall active')
    teacher_rollcall_activate.add_argument('rollcall_id')
    teacher_rollcall_activate.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_stop = teacher_rollcall_subcommands.add_parser('stop', help='stop a rollcall')
    teacher_rollcall_stop.add_argument('rollcall_id')
    teacher_rollcall_stop.add_argument('--type', choices=('manual', 'number', 'radar', 'qr', 'self_registration', 'self-registration'), default='manual', help='rollcall type used to choose the stop endpoint')
    teacher_rollcall_stop.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_students = teacher_rollcall_subcommands.add_parser('students', help='show student rollcall statuses')
    teacher_rollcall_students.add_argument('rollcall_id')
    teacher_rollcall_students.add_argument('--action', default='', help='optional action, e.g. manual_refresh')
    teacher_rollcall_students.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_info = teacher_rollcall_subcommands.add_parser('info', help='show detail/lite/students/count/answers/result for one rollcall')
    teacher_rollcall_info.add_argument('rollcall_id')
    teacher_rollcall_info.add_argument('--action', default='', help='optional action for student_rollcalls, e.g. manual_refresh')
    teacher_rollcall_info.add_argument('--page', type=int, default=1)
    teacher_rollcall_info.add_argument('--page-size', type=int, default=20)
    teacher_rollcall_info.add_argument('--rollcall-status', default='', help='optional status filter for paged students')
    teacher_rollcall_info.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_pagination = teacher_rollcall_subcommands.add_parser('pagination-students', help='show paged student rollcall statuses')
    teacher_rollcall_pagination.add_argument('rollcall_id')
    teacher_rollcall_pagination.add_argument('--page', type=int, default=1)
    teacher_rollcall_pagination.add_argument('--page-size', type=int, default=20)
    teacher_rollcall_pagination.add_argument('--rollcall-status', default='', help='optional status filter')
    teacher_rollcall_pagination.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_count = teacher_rollcall_subcommands.add_parser('count', help='show student rollcall status counts')
    teacher_rollcall_count.add_argument('rollcall_id')
    teacher_rollcall_count.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_result = teacher_rollcall_subcommands.add_parser('result', help='show realtime rollcall status result')
    teacher_rollcall_result.add_argument('rollcall_id')
    teacher_rollcall_result.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_student_history = teacher_rollcall_subcommands.add_parser('student-history', help='show one student rollcall history')
    teacher_rollcall_student_history.add_argument('--course-id', required=True, help='course id')
    teacher_rollcall_student_history.add_argument('--student-id', required=True, help='student id')
    teacher_rollcall_student_history.add_argument('--page', type=int, default=1)
    teacher_rollcall_student_history.add_argument('--page-size', type=int, default=10)
    teacher_rollcall_student_history.add_argument('--rollcall-ids', default='', help='optional comma-separated rollcall ids filter')
    teacher_rollcall_student_history.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_raw_update = teacher_rollcall_subcommands.add_parser('update', help='update one rollcall from a raw JSON payload')
    teacher_rollcall_raw_update.add_argument('rollcall_id')
    teacher_rollcall_raw_update.add_argument('--payload-json', required=True, help='JSON object payload to send')
    teacher_rollcall_raw_update.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_update = teacher_rollcall_subcommands.add_parser('update-students', help='update student rollcall statuses')
    teacher_rollcall_update.add_argument('rollcall_id')
    teacher_rollcall_update.add_argument('--input', default='', help='JSON list/path for student_rollcalls')
    teacher_rollcall_update.add_argument('--student-id', default='', help='single student id when --input is omitted')
    teacher_rollcall_update.add_argument('--status', default='on_call_fine', help='single student rollcall status')
    teacher_rollcall_update.add_argument('--rollcall-status', default='in_progress', help='overall rollcall status')
    teacher_rollcall_update.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_update_history = teacher_rollcall_subcommands.add_parser('update-student-history', help='update one student statuses across rollcalls')
    teacher_rollcall_update_history.add_argument('--course-id', required=True, help='course id')
    teacher_rollcall_update_history.add_argument('--student-id', required=True, help='student id')
    teacher_rollcall_update_history.add_argument('--input', default='', help='JSON list/path for student_rollcalls')
    teacher_rollcall_update_history.add_argument('--student-rollcall-id', default='', help='single student_rollcall_id when --input is omitted')
    teacher_rollcall_update_history.add_argument('--status', default='on_call_fine', help='single student status')
    teacher_rollcall_update_history.add_argument('--force', action='store_true', help='skip local teacher role gate and let the server decide')
    teacher_rollcall_update_history.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_radar_position = teacher_rollcall_subcommands.add_parser('update-radar-position', help='update radar rollcall position')
    teacher_rollcall_radar_position.add_argument('rollcall_id')
    teacher_rollcall_radar_position.add_argument('--payload-json', default='', help='JSON object payload to send')
    teacher_rollcall_radar_position.add_argument('--latitude', type=float, default=None, help='radar latitude when --payload-json is omitted')
    teacher_rollcall_radar_position.add_argument('--longitude', type=float, default=None, help='radar longitude when --payload-json is omitted')
    teacher_rollcall_radar_position.add_argument('--altitude', type=float, default=None, help='optional radar altitude')
    teacher_rollcall_radar_position.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_answer_qr = teacher_rollcall_subcommands.add_parser('answer-qr', help='submit a QR rollcall payload')
    teacher_rollcall_answer_qr.add_argument('rollcall_id')
    teacher_rollcall_answer_qr.add_argument('--payload-json', required=True, help='JSON object payload to send')
    teacher_rollcall_answer_qr.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_answer_number = teacher_rollcall_subcommands.add_parser('answer-number', help='submit a number rollcall payload')
    teacher_rollcall_answer_number.add_argument('rollcall_id')
    teacher_rollcall_answer_number.add_argument('--payload-json', required=True, help='JSON object payload to send')
    teacher_rollcall_answer_number.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_answer_radar = teacher_rollcall_subcommands.add_parser('answer-radar', help='submit a radar rollcall payload')
    teacher_rollcall_answer_radar.add_argument('rollcall_id')
    teacher_rollcall_answer_radar.add_argument('--payload-json', required=True, help='JSON object payload to send')
    teacher_rollcall_answer_radar.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_answer_self_registration = teacher_rollcall_subcommands.add_parser('answer-self-registration', help='submit a self-registration rollcall payload')
    teacher_rollcall_answer_self_registration.add_argument('rollcall_id')
    teacher_rollcall_answer_self_registration.add_argument('--payload-json', required=True, help='JSON object payload to send')
    teacher_rollcall_answer_self_registration.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_publish = teacher_rollcall_subcommands.add_parser('publish', help='publish one rollcall from a JSON payload')
    teacher_rollcall_publish.add_argument('rollcall_id')
    teacher_rollcall_publish.add_argument('--payload-json', required=True, help='JSON object payload to send')
    teacher_rollcall_publish.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_publish_must = teacher_rollcall_subcommands.add_parser('publish-must', help='publish-must one rollcall from a JSON payload')
    teacher_rollcall_publish_must.add_argument('rollcall_id')
    teacher_rollcall_publish_must.add_argument('--payload-json', required=True, help='JSON object payload to send')
    teacher_rollcall_publish_must.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_create_merged = teacher_rollcall_subcommands.add_parser('create-merged', help='create a merged rollcall from a JSON payload')
    teacher_rollcall_create_merged.add_argument('--payload-json', required=True, help='JSON object payload to send')
    teacher_rollcall_create_merged.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_update_merged = teacher_rollcall_subcommands.add_parser('update-merged-students', help='update merged rollcall student records from a JSON payload')
    teacher_rollcall_update_merged.add_argument('--payload-json', required=True, help='JSON object payload to send')
    teacher_rollcall_update_merged.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_setting = teacher_rollcall_subcommands.add_parser('setting', help='update course rollcall scoring/settings')
    teacher_rollcall_setting.add_argument('--course-id', required=True, help='course id')
    teacher_rollcall_setting.add_argument('--payload-json', required=True, help='JSON object payload to send')
    teacher_rollcall_setting.add_argument('--force', action='store_true', help='skip local teacher role gate and let the server decide')
    teacher_rollcall_setting.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_score = teacher_rollcall_subcommands.add_parser('score', help='update one enrollment rollcall score')
    teacher_rollcall_score.add_argument('enrollment_id')
    teacher_rollcall_score.add_argument('--score', required=True, help='rollcall score value')
    teacher_rollcall_score.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_import = teacher_rollcall_subcommands.add_parser('import', help='import course rollcalls from a JSON payload')
    teacher_rollcall_import.add_argument('--course-id', required=True, help='course id')
    teacher_rollcall_import.add_argument('--payload-json', required=True, help='JSON object payload to send')
    teacher_rollcall_import.add_argument('--force', action='store_true', help='skip local teacher role gate and let the server decide')
    teacher_rollcall_import.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_grade = teacher_rollcall_subcommands.add_parser('grade', help='calculate grades for one or more rollcalls')
    teacher_rollcall_grade.add_argument('--rollcall-ids', required=True, help='comma-separated rollcall ids')
    teacher_rollcall_grade.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_export_stat = teacher_rollcall_subcommands.add_parser('export-stat-report', help='download rollcall statistics export')
    teacher_rollcall_export_stat.add_argument('--kind', choices=('rollcall', 'rollcall-by-class'), default='rollcall')
    teacher_rollcall_export_stat.add_argument('--method', choices=('GET', 'POST'), default='POST')
    teacher_rollcall_export_stat.add_argument('--payload-json', default='', help='JSON object export filter; defaults to {}')
    teacher_rollcall_export_stat.add_argument('--output', required=True, help='output file path')
    teacher_rollcall_export_stat.add_argument('--overwrite', action='store_true', help='overwrite existing output')
    teacher_rollcall_export_stat.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_module_list = teacher_rollcall_subcommands.add_parser('module-list', help='show course module rollcalls')
    teacher_rollcall_module_list.add_argument('--course-id', required=True, help='course id')
    teacher_rollcall_module_list.add_argument('--params-json', default='', help='optional JSON object query params')
    teacher_rollcall_module_list.add_argument('--force', action='store_true', help='skip local teacher role gate and let the server decide')
    teacher_rollcall_module_list.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_alert_log = teacher_rollcall_subcommands.add_parser('alert-log', help='show rollcalls linked to an alert log')
    teacher_rollcall_alert_log.add_argument('alert_log_id')
    teacher_rollcall_alert_log.add_argument('--page', type=int, default=1)
    teacher_rollcall_alert_log.add_argument('--page-size', type=int, default=20)
    teacher_rollcall_alert_log.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_timetable_stat = teacher_rollcall_subcommands.add_parser('timetable-stat', help='show timetable rollcall statistics')
    teacher_rollcall_timetable_stat.add_argument('timetable_id')
    teacher_rollcall_timetable_stat.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_notification_count = teacher_rollcall_subcommands.add_parser('notification-count', help='show rollcall alert unread notification count')
    teacher_rollcall_notification_count.add_argument('--user-id', required=True, help='notification user id')
    teacher_rollcall_notification_count.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_qrcode = teacher_rollcall_subcommands.add_parser('qrcode', help='generate a QR code image through the server')
    teacher_rollcall_qrcode.add_argument('--url', required=True, help='text or URL to encode')
    teacher_rollcall_qrcode.add_argument('--output', default='', help='optional output image path')
    teacher_rollcall_qrcode.add_argument('--include-body', action='store_true', help='include base64 image body in JSON')
    teacher_rollcall_qrcode.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_delete = teacher_rollcall_subcommands.add_parser('delete', help='delete a rollcall')
    teacher_rollcall_delete.add_argument('rollcall_id')
    teacher_rollcall_delete.add_argument('--yes', action='store_true', help='confirm deletion')
    teacher_rollcall_delete.add_argument('--json', action='store_true', help='print JSON')
    teacher_attendance = teacher_subcommands.add_parser('attendance', help='teacher attendance/stat export tools')
    teacher_attendance_subcommands = teacher_attendance.add_subparsers(dest='teacher_attendance_command')
    teacher_attendance_export = teacher_attendance_subcommands.add_parser('export', help='download attendance export')
    teacher_attendance_export.add_argument('--file-type', default='xlsx', help='export file type, e.g. xlsx')
    teacher_attendance_export.add_argument('--payload-json', required=True, help='JSON object payload to send')
    teacher_attendance_export.add_argument('--output', required=True, help='output file path')
    teacher_attendance_export.add_argument('--overwrite', action='store_true', help='overwrite existing output')
    teacher_attendance_export.add_argument('--json', action='store_true', help='print JSON')
    teacher_attendance_stat = teacher_attendance_subcommands.add_parser('stat', help='show lesson/student/teacher rollcall stat')
    teacher_attendance_stat.add_argument('--kind', choices=('lesson', 'student', 'teacher'), required=True)
    teacher_attendance_stat.add_argument('--params-json', default='', help='optional JSON object query params')
    teacher_attendance_stat.add_argument('--json', action='store_true', help='print JSON')
    teacher_attendance_departments = teacher_attendance_subcommands.add_parser('departments', help='show or export department attendance')
    teacher_attendance_departments.add_argument('--payload-json', required=True, help='JSON object payload to send')
    teacher_attendance_departments.add_argument('--page', type=int, default=1)
    teacher_attendance_departments.add_argument('--page-size', type=int, default=20)
    teacher_attendance_departments.add_argument('--file-type', default='xlsx', help='export file type when --output is set')
    teacher_attendance_departments.add_argument('--output', default='', help='download export instead of list when set')
    teacher_attendance_departments.add_argument('--overwrite', action='store_true', help='overwrite existing output')
    teacher_attendance_departments.add_argument('--json', action='store_true', help='print JSON')
    teacher_attendance_user_departments = teacher_attendance_subcommands.add_parser('user-departments', help='show or export department user attendance')
    teacher_attendance_user_departments.add_argument('--params-json', default='', help='optional JSON object query params')
    teacher_attendance_user_departments.add_argument('--page', type=int, default=1)
    teacher_attendance_user_departments.add_argument('--page-size', type=int, default=20)
    teacher_attendance_user_departments.add_argument('--file-type', default='xlsx', help='export file type when --output is set')
    teacher_attendance_user_departments.add_argument('--output', default='', help='download export instead of list when set')
    teacher_attendance_user_departments.add_argument('--overwrite', action='store_true', help='overwrite existing output')
    teacher_attendance_user_departments.add_argument('--json', action='store_true', help='print JSON')
    teacher_face_check = teacher_subcommands.add_parser('face-check', help='face-check diagnostic wrappers')
    teacher_face_check_subcommands = teacher_face_check.add_subparsers(dest='teacher_face_check_command')
    teacher_face_check_create = teacher_face_check_subcommands.add_parser('create', help='create a face-check record')
    teacher_face_check_create.add_argument('--payload-json', required=True, help='JSON object payload to send')
    teacher_face_check_create.add_argument('--json', action='store_true', help='print JSON')
    teacher_face_check_check = teacher_face_check_subcommands.add_parser('check', help='check face-check record status')
    teacher_face_check_check.add_argument('--params-json', default='', help='optional JSON object query params')
    teacher_face_check_check.add_argument('--json', action='store_true', help='print JSON')
    teacher_face_check_verify = teacher_face_check_subcommands.add_parser('verify', help='verify face-check record status')
    teacher_face_check_verify.add_argument('--params-json', default='', help='optional JSON object query params')
    teacher_face_check_verify.add_argument('--json', action='store_true', help='print JSON')
    teacher_qr_auth = teacher_subcommands.add_parser('qr-auth', help='QR/auth adjacent raw wrappers')
    teacher_qr_auth_subcommands = teacher_qr_auth.add_subparsers(dest='teacher_qr_auth_command')
    teacher_qr_auth_login = teacher_qr_auth_subcommands.add_parser('qrcode-login', help='raw /api/qrcode/login request')
    teacher_qr_auth_login.add_argument('--method', choices=('GET', 'POST'), default='GET')
    teacher_qr_auth_login.add_argument('--params-json', default='', help='optional JSON object query params')
    teacher_qr_auth_login.add_argument('--payload-json', default='', help='JSON object payload for POST')
    teacher_qr_auth_login.add_argument('--json', action='store_true', help='print JSON')
    teacher_qr_auth_scan = teacher_qr_auth_subcommands.add_parser('scan', help='submit a QR-code scan payload')
    teacher_qr_auth_scan.add_argument('--payload-json', required=True, help='JSON object payload to send')
    teacher_qr_auth_scan.add_argument('--json', action='store_true', help='print JSON')
    teacher_qr_auth_wechat = teacher_qr_auth_subcommands.add_parser('wechat-url', help='build a WeChat QR connect URL')
    teacher_qr_auth_wechat.add_argument('--appid', required=True, help='WeChat app id')
    teacher_qr_auth_wechat.add_argument('--redirect-uri', default='', help='optional redirect_uri')
    teacher_qr_auth_wechat.add_argument('--scope', default='snsapi_login', help='WeChat QR connect scope')
    teacher_qr_auth_wechat.add_argument('--state', default='', help='optional state')
    teacher_qr_auth_wechat.add_argument('--base-url', default='https://open.weixin.qq.com', help='WeChat connect base URL')
    teacher_qr_auth_wechat.add_argument('--json', action='store_true', help='print JSON')
    teacher_qr_auth_broker = teacher_qr_auth_subcommands.add_parser('identity-broker', help='post to tronclass-qrcode identity broker endpoint')
    teacher_qr_auth_broker.add_argument('--realm', required=True, help='identity realm')
    teacher_qr_auth_broker.add_argument('--params-json', default='', help='optional JSON object query params')
    teacher_qr_auth_broker.add_argument('--payload-json', required=True, help='JSON object payload to send')
    teacher_qr_auth_broker.add_argument('--json', action='store_true', help='print JSON')
    subcommands.add_parser('refresh', help='delete cached cookies for the active profile')
    dashboard_parser = subcommands.add_parser('dashboard', help='show a lightweight terminal dashboard')
    dashboard_parser.add_argument('--once', action='store_true', help='render once and exit')
    dashboard_parser.add_argument('--interval', type=float, default=2.0, help='refresh interval seconds')
    dashboard_parser.add_argument('--json', action='store_true', help='print one machine-readable snapshot')
    debug_parser = subcommands.add_parser('debug-capture', help='capture one sanitized rollcall API snapshot for diagnostics')
    debug_parser.add_argument('--output', default='', help='JSONL output path; defaults to state/debug-capture/rollcalls.jsonl')
    research_parser = subcommands.add_parser('research', help='run opt-in research diagnostics')
    research_subcommands = research_parser.add_subparsers(dest='research_command')
    research_status = research_subcommands.add_parser('status', help='show research mode gates')
    research_status.add_argument('--json', action='store_true', help='print JSON')
    research_api = research_subcommands.add_parser('api', help='capture sanitized read-only API metadata')
    research_api.add_argument('--target', default='all', help='safe target: home, rollcalls, semester, courses, or all')
    research_api.add_argument('--output', default='', help='optional JSONL output path')
    research_api.add_argument('--json', action='store_true', help='print JSON')
    research_probe = research_subcommands.add_parser('probe', help='probe risky endpoints as sanitized read-only shape metadata')
    research_probe.add_argument('probe_target', nargs='?', default='student_rollcalls', help='probe target: student_rollcalls, lite, or ongoing_rollcalls')
    research_probe.add_argument('--rollcall-id', default='', help='rollcall id to probe (required for student_rollcalls and lite; ignored for ongoing_rollcalls)')
    research_probe.add_argument('--output', default='', help='optional JSONL output path')
    research_probe.add_argument('--json', action='store_true', help='print JSON')
    research_browser_check = research_subcommands.add_parser('browser-check', help='check optional Playwright availability')
    research_browser_check.add_argument('--json', action='store_true', help='print JSON')
    research_browser_capture = research_subcommands.add_parser('browser-capture', help='capture sanitized browser request metadata without logging in')
    research_browser_capture.add_argument('--target', choices=('login', 'home'), default='home')
    research_browser_capture.add_argument('--json', action='store_true', help='print JSON')
    qr_parser = subcommands.add_parser('qr', help='submit, preview, or scan TronClass QR payloads')
    qr_parser.add_argument('qr_args', nargs='*', help='payload, or subcommands: paste/pending/scan')
    qr_parser.add_argument('--yes', action='store_true', help='skip QR paste confirmation')
    qr_parser.add_argument('--all', dest='fanout_all', action='store_true', help='submit to all matching pending profiles')
    qr_parser.add_argument('--json', action='store_true', help='print JSON for preview/pending')
    qr_parser.add_argument('--host', default='', help='local scanner host')
    qr_parser.add_argument('--port', type=int, default=0, help='local scanner port')
    qr_parser.add_argument('--open', action='store_true', help='open local scanner in browser')
    qr_parser.add_argument('--image', default='', help='decode QR payload from a static image file')
    qr_parser.add_argument('--rollcall-id', default='', help='rollcall id for `qr data-probe`')
    qr_parser.add_argument('--samples', type=int, default=5, help='`qr data-probe` random-hash samples (timestamp kept correct)')
    qr_parser.add_argument('--timestamp', default='', help='`qr data-probe` unix timestamp prefix (default: derive from server rollcall_time + Date)')
    logs_parser = subcommands.add_parser('logs', help='inspect sanitized local logs')
    logs_subcommands = logs_parser.add_subparsers(dest='logs_command')
    logs_tail = logs_subcommands.add_parser('tail', help='print recent JSONL log records')
    logs_tail.add_argument('--limit', type=int, default=20)
    logs_tail.add_argument('--json', action='store_true')
    logs_summary = logs_subcommands.add_parser('summarize', help='summarize log records')
    logs_summary.add_argument('--limit', type=int, default=20, help='recent records to include in notable event summary')
    logs_summary.add_argument('--json', action='store_true')
    logs_summary_alias = logs_subcommands.add_parser('summary', help='alias for summarize')
    logs_summary_alias.add_argument('--limit', type=int, default=20, help='recent records to include in notable event summary')
    logs_summary_alias.add_argument('--json', action='store_true')
    logs_export = logs_subcommands.add_parser('export', help='write a redacted debug bundle')
    logs_export.add_argument('--output', default='', help='output zip path')
    logs_export.add_argument('--json', action='store_true')
    logs_export.add_argument('--limit', type=int, default=50)
    account_parser = subcommands.add_parser('account', help='manage account profiles')
    account_subcommands = account_parser.add_subparsers(dest='account_command')
    account_list = account_subcommands.add_parser('list', help='list account profiles')
    account_list.add_argument('--json', action='store_true')
    account_show_parser = account_subcommands.add_parser('show', help='show one account profile')
    account_show_parser.add_argument('name', nargs='?', default='', help='profile name; defaults to active')
    account_show_parser.add_argument('--json', action='store_true')
    account_state_parser = account_subcommands.add_parser('state', help='show runtime state for one account profile')
    account_state_parser.add_argument('name', nargs='?', default='', help='profile name; defaults to active')
    account_state_parser.add_argument('--json', action='store_true')
    account_doctor_parser = account_subcommands.add_parser('doctor', help='diagnose one account profile')
    account_doctor_parser.add_argument('name', nargs='?', default='', help='profile name; defaults to active')
    account_doctor_parser.add_argument('--json', action='store_true')
    account_add = account_subcommands.add_parser('add', help='add or update an account profile')
    account_add.add_argument('name', help='profile name')
    account_add.add_argument('--user', help='student id')
    account_add.add_argument('--password', help='password; omit to prompt securely')
    account_add.add_argument('--store', choices=('keyring', 'env', 'config', 'none'), default='keyring', help='where to store the password')
    account_add.add_argument('--label', default='', help='optional display label')
    account_add.add_argument('--no-switch', action='store_true', help='do not switch to this profile')
    account_switch = account_subcommands.add_parser('switch', help='switch active profile')
    account_switch.add_argument('name', help='profile name')
    account_remove = account_subcommands.add_parser('remove', help='remove an account profile')
    account_remove.add_argument('name', help='profile name')
    account_bind = account_subcommands.add_parser('bind', help='bind adapter user id to a profile')
    account_bind.add_argument('adapter', choices=('discord', 'line', 'telegram'))
    account_bind.add_argument('external_user_id')
    account_bind.add_argument('profile')
    account_bind.add_argument('--channel', default='')
    account_unbind = account_subcommands.add_parser('unbind', help='remove adapter binding')
    account_unbind.add_argument('adapter', choices=('discord', 'line', 'telegram'))
    account_unbind.add_argument('external_user_id')
    bot_parser = subcommands.add_parser('bot', help='run bot adapter services')
    bot_subcommands = bot_parser.add_subparsers(dest='bot_command')
    bot_serve = bot_subcommands.add_parser('serve', help='serve bot adapter webhooks')
    bot_serve.add_argument('--host', default='127.0.0.1', help='bind host')
    bot_serve.add_argument('--port', type=int, default=8787, help='bind port')
    bot_serve.add_argument('--adapter', choices=('all', 'generic', 'line', 'discord'), default='all')
    bot_serve.add_argument('--json', action='store_true', help='print startup metadata as JSON')
    bot_schema = bot_subcommands.add_parser('discord-schema', help='print Discord slash command schema')
    bot_schema.add_argument('--json', action='store_true', help='print schema as JSON')
    bot_discord_sync = bot_subcommands.add_parser('discord-sync', help='sync Discord slash command schema')
    bot_discord_sync.add_argument('--apply', action='store_true', help='apply schema to Discord; default is dry-run')
    bot_discord_sync.add_argument('--dry-run', action='store_true', help='show planned sync without network')
    bot_discord_sync.add_argument('--json', action='store_true', help='print JSON')
    bot_discord_gateway = bot_subcommands.add_parser('discord-gateway', help='run optional Discord Gateway')
    bot_discord_gateway.add_argument('--dry-run', action='store_true', help='print safe health without connecting')
    bot_discord_gateway.add_argument('--json', action='store_true', help='print JSON')
    return parser
