import asyncio
import argparse
import copy
import getpass
import hashlib
import importlib.util
import json
import os
import random
import ssl
import string
import sys
import time
import traceback
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional, Tuple

try:
    import aiohttp
except ModuleNotFoundError:  # pragma: no cover - dependency-missing CLI fallback
    class _MissingAiohttp:
        class ClientError(Exception):
            pass

        class ContentTypeError(Exception):
            pass

        class ClientSession:
            def __init__(self, *args, **kwargs) -> None:
                raise RuntimeError("aiohttp is not installed. Run `pip install -r requirements.txt`.")

        class TCPConnector:
            def __init__(self, *args, **kwargs) -> None:
                raise RuntimeError("aiohttp is not installed. Run `pip install -r requirements.txt`.")

    aiohttp = _MissingAiohttp()  # type: ignore
try:
    import yaml
except ModuleNotFoundError:  # pragma: no cover - dependency-missing CLI fallback
    class _MissingYaml:
        class YAMLError(Exception):
            pass

        @staticmethod
        def safe_load(_stream: Any) -> Dict[str, Any]:
            return {}

        @staticmethod
        def safe_dump(data: Any, stream: Any, **_kwargs: Any) -> None:
            stream.write(str(data))

    yaml = _MissingYaml()  # type: ignore

try:
    from troTHU.account_store import (
        clear_session_cookies,
        cookie_cache_enabled,
        cookie_path,
        get_active_profile,
        get_keyring_password,
        keyring_available,
        list_profiles,
        load_session_cookies,
        normalize_accounts_config,
        normalize_profile_name,
        remove_profile,
        save_session_cookies,
        set_keyring_password,
        set_profile,
        switch_profile,
    )
    from troTHU.account_runtime_store import (
        load_runtime_state,
        mark_check_result,
        mark_login_result,
        mark_monitor_state,
        mark_profile_error,
        runtime_profile_summary,
        runtime_state_path,
    )
    from troTHU.adapter_bridge import (
        AdapterBinding,
        binding_key,
        map_adapter_command,
    )
    from troTHU.app_blueprint import (
        build_app_blueprint,
        format_app_blueprint_summary,
        validate_app_blueprint,
    )
    from troTHU.app_shell import run_app_shell
    from troTHU.app_shell_polish import (
        build_shell_action_catalog,
        build_shell_drilldown,
        build_shell_ui_model,
    )
    from troTHU.bot_runtime import normalize_admins_config
    from troTHU.connection_probe import (
        run_connection_probe,
        sanitize_probe_url,
    )
    from troTHU.course_discovery import (
        CourseDiscoveryError,
        discover_courses,
    )
    from troTHU.local_scanner import run_scanner_server
    from troTHU.notification_bus import dispatch_notification_event
    from troTHU.notification_delivery import (
        NotificationRequest,
        NotificationSendError,
        build_notification_requests as build_notification_requests_from_config,
        normalize_telegram_bot_key,
        send_notification_request,
    )
    from troTHU.observability import (
        build_observability_snapshot,
        classify_recent_events,
        format_dashboard_snapshot,
        format_log_summary,
    )
    from troTHU.package_diagnostics import build_package_diagnostic_report
    from troTHU.provider_ready_gate import (
        build_provider_ready_gate,
        format_provider_ready_gate,
    )
    from troTHU.provider_verification import (
        build_provider_fixture_template,
        build_provider_verification_checklist,
        summarize_provider_verification,
        validate_provider_fixture,
    )
    from troTHU.provider_fixture_review import (
        build_provider_fixture_review,
        build_provider_fixture_review_template,
        format_provider_fixture_review,
        review_provider_fixture_dir,
        review_provider_fixture_file,
    )
    from troTHU.pending_qr import (
        DEFAULT_PENDING_QR_PROVIDER,
        add_pending_qr,
        list_pending_qr,
        match_pending_qr,
        remove_pending_qr,
    )
    from troTHU.qr_rollcall import (
        QrCodeData,
        answer_qr_rollcall,
        parse_qr_payload,
        parse_qr_payload_with_diagnostics,
    )
    from troTHU.number_rollcall import (
        NumberAttemptStatus,
        NumberCodeLookup,
        classify_number_response,
        coerce_number_code,
        parse_number_code_payload,
    )
    from troTHU.providers import (
        DEFAULT_PROVIDER,
        get_provider,
        list_all_providers,
        list_supported_providers,
        normalize_provider_config,
        provider_support_report,
        provider_registry_config,
        tronclass_api_endpoints,
    )
    from troTHU.research_mode import normalize_research_mode_config
    from troTHU.research_sandbox import (
        ResearchCaptureError,
        ResearchGateError,
        append_research_capture,
        build_browser_capture_metadata,
        build_research_status,
        capture_browser_target_metadata,
        capture_research_api_target,
        capture_rollcall_probe,
        capture_student_rollcalls_probe,
        ensure_research_allowed,
    )
    from troTHU.webview_sync import (
        WebViewSyncError,
        build_webview_cookie_preview,
        build_webview_sync_status,
        import_webview_cookies,
        parse_webview_cookie_export,
    )
    from troTHU.debug_capture import append_debug_capture
    from troTHU.radar_solver import (
        DEFAULT_BOUNDARY_POINTS,
        DistanceObservation,
        GeoPoint,
        RadarGeometryError,
        build_probe_plan,
        choose_fourth_probe,
        final_candidate_points,
        solve_position,
    )
    from troTHU.radar_rollcall import (
        build_radar_answer_payload,
        build_radar_attempt_diagnostic,
        parse_radar_lite_payload,
    )
    from troTHU.radar_map_assist import build_radar_map_assist
    from troTHU.release_checklist import (
        build_release_build_plan,
        build_release_checklist,
        format_release_checklist,
    )
    from troTHU.release_builder import (
        format_release_build_summary,
        run_release_build_pipeline,
    )
    from troTHU.real_validation import (
        append_local_smoke_validation_records,
        append_real_validation_record,
        build_local_smoke_validation_records,
        build_real_validation_checklist,
        format_real_validation_summary,
        run_local_validation_smoke,
        summarize_real_validation,
    )
    from troTHU.discord_adapter import sync_discord_command_schema
    from troTHU.discord_gateway import build_gateway_health, run_discord_gateway
    from troTHU.teacher_runtime import (
        TEACHER_ENDPOINT_GROUPS,
        TeacherDiscoveryError,
        build_teacher_activity_report,
        build_teacher_classroom_report,
        build_teacher_course_report,
        build_teacher_exam_report,
        build_teacher_group_set_report,
        build_teacher_questionnaire_report,
        build_teacher_rollcall_report,
        activate_teacher_rollcall,
        add_teacher_activity_comment,
        add_teacher_shared_resource_comment,
        answer_teacher_number_rollcall,
        answer_teacher_qr_rollcall,
        answer_teacher_radar_rollcall,
        batch_delete_teacher_entries,
        batch_delete_teacher_slides,
        batch_save_teacher_shared_resources,
        cancel_recommend_teacher_submission,
        check_teacher_activity_dependents,
        check_teacher_module_dependents,
        check_teacher_syllabus_dependents,
        classify_account_type,
        classify_teacher_course,
        clear_teacher_air_credit_remaining_credits,
        copy_teacher_group_set,
        create_teacher_entry,
        create_teacher_course_estimate,
        create_teacher_course_estimate_reply,
        create_teacher_activity,
        create_teacher_air_credit_assignments,
        create_teacher_bulletin,
        create_teacher_classroom_exam,
        create_teacher_course_package,
        create_teacher_group,
        create_teacher_group_set,
        create_teacher_courseware_quiz_subjects,
        create_teacher_module,
        create_teacher_merged_rollcall,
        create_teacher_module_rollcall,
        create_teacher_syllabus,
        create_teacher_custom_score_item,
        create_teacher_exam,
        create_teacher_rollcall,
        create_teacher_rubric,
        create_teacher_questionnaire_subject,
        create_teacher_resource_group,
        create_teacher_subject_lib,
        create_teacher_teaching_calendar,
        delete_teacher_bulletin,
        delete_teacher_classroom,
        delete_teacher_classroom_subjects,
        delete_teacher_course_package,
        delete_teacher_course_estimate,
        delete_teacher_course_estimate_reply,
        delete_teacher_entry,
        delete_teacher_activity,
        delete_teacher_activity_comment,
        delete_teacher_activity_comment_reply,
        delete_teacher_activity_resource,
        delete_teacher_questionnaire_subject,
        delete_teacher_resource_group,
        delete_teacher_resource_group_folder,
        delete_teacher_resource_group_members,
        delete_teacher_resource_group_resource,
        delete_teacher_shared_resource,
        delete_teacher_shared_resource_comment,
        delete_teacher_slide,
        delete_teacher_slide_record,
        delete_teacher_subject_lib,
        delete_teacher_subject_lib_subjects,
        delete_teacher_group,
        delete_teacher_group_member,
        delete_teacher_group_set,
        delete_teacher_module,
        delete_teacher_rollcall,
        delete_teacher_activities,
        delete_teacher_calendar_meeting,
        delete_teacher_custom_score_item,
        delete_teacher_exams,
        delete_teacher_rubrics,
        delete_teacher_syllabus,
        delete_teacher_teaching_calendar,
        delete_teacher_outline_setting_option,
        discover_teacher_context,
        download_teacher_api_path,
        download_teacher_api_request,
        download_teacher_qrcode,
        download_teacher_air_credit_stats_export,
        download_teacher_category_topics_export,
        download_teacher_cloud_classroom_live_classes_export,
        download_teacher_course_stat_students_export,
        download_teacher_ai_ppt_user_usage_export,
        download_teacher_department_attendance_export,
        download_teacher_department_user_attendance_export,
        download_teacher_management_calendar_meeting_export,
        download_teacher_questionnaire_export,
        download_teacher_shared_resource_blob,
        download_teacher_shared_resource_stat_export,
        download_teacher_shared_resource_subject_lib_export,
        download_teacher_shared_resource_video_stat_export,
        download_teacher_stat_attendance_export_to,
        download_teacher_stat_courses_export_to,
        download_teacher_stat_vtrses_data_export,
        download_teacher_stat_report_export,
        download_teacher_tencent_meeting_statistics_export,
        download_teacher_topic_export,
        download_teacher_third_part_upload,
        download_teacher_upload_blob,
        download_teacher_upload_modified_image,
        download_teacher_upload_reference_blob,
        download_teacher_upload_swf,
        download_teacher_upload_thumbnail,
        download_teacher_wedrive_file,
        upload_teacher_file,
        fetch_teacher_api_path,
        fetch_teacher_activity_uploads_license,
        fetch_teacher_ai_ppt_report,
        fetch_teacher_air_credit_report,
        fetch_teacher_authoring_report,
        fetch_teacher_calendar_meetings,
        fetch_teacher_cc_license_groups,
        fetch_teacher_cc_license_map,
        fetch_teacher_catalog_report,
        fetch_teacher_completion_criteria,
        fetch_teacher_course_estimate_replies,
        fetch_teacher_course_estimate_user,
        fetch_teacher_course_package_course,
        fetch_teacher_course_completion_criteria,
        fetch_teacher_course_rollcall_detail,
        fetch_teacher_courseware_quizzes,
        fetch_teacher_courseware_quiz_settings,
        fetch_teacher_courseware_quiz_subjects,
        fetch_teacher_course_statistics,
        fetch_teacher_department_report,
        fetch_teacher_entries,
        fetch_teacher_entry,
        fetch_teacher_entry_references,
        fetch_teacher_endpoint,
        fetch_teacher_forum_categories,
        fetch_teacher_forum_category,
        fetch_teacher_management_calendar_meetings,
        fetch_teacher_media_report,
        fetch_teacher_org_bulletin_report,
        fetch_teacher_platform_report,
        fetch_teacher_published_slides,
        fetch_teacher_questionnaire_submissions,
        fetch_teacher_resource_group,
        fetch_teacher_resource_group_folders,
        fetch_teacher_resource_group_members,
        fetch_teacher_resource_group_resources,
        fetch_teacher_resource_group_rubrics,
        fetch_teacher_resource_group_subject_libs,
        fetch_teacher_resource_groups,
        fetch_teacher_rollcall_endpoint,
        fetch_teacher_rollcall_count,
        fetch_teacher_rollcall_status_result,
        fetch_teacher_rollcall_students_page,
        fetch_teacher_ongoing_student_rollcalls,
        fetch_teacher_leave_record,
        fetch_teacher_student_rollcalls,
        fetch_teacher_shared_resource_classifications,
        fetch_teacher_shared_resource_collections,
        fetch_teacher_shared_resource_comments,
        fetch_teacher_shared_resource_followers,
        fetch_teacher_shared_resource_recommendations,
        fetch_teacher_shared_resource_tags,
        fetch_teacher_shared_resource_track_users,
        fetch_teacher_shared_resources,
        fetch_teacher_slide,
        fetch_teacher_slide_export_status,
        fetch_teacher_slide_records,
        fetch_teacher_slides,
        fetch_teacher_subject_lib_folders,
        fetch_teacher_subject_lib_knowledge_nodes,
        fetch_teacher_subject_lib_statistic,
        fetch_teacher_subject_lib_subjects,
        fetch_teacher_subject_libs,
        fetch_teacher_teaching_calendars,
        fetch_teacher_user_resource_folder_info,
        fetch_teacher_user_resources,
        fetch_teacher_vtrs_report,
        grade_teacher_rollcalls,
        grade_teacher_submission,
        import_teacher_course_groups,
        import_teacher_course_package,
        import_teacher_enrollments,
        import_teacher_item_scores,
        import_teacher_questionnaire_subjects,
        import_teacher_rollcalls,
        import_teacher_scores,
        import_teacher_seat_numbers,
        move_teacher_subject_lib_subjects,
        move_teacher_subject_libs,
        notify_teacher_outline_editing,
        operate_teacher_activity_comments,
        recommend_teacher_submissions,
        reply_teacher_activity_comment,
        resort_teacher_activity,
        copy_teacher_subject_libs_to_courseware_quiz,
        copy_teacher_subject_lib,
        copy_teacher_subject_libs_to_user,
        create_teacher_calendar_meeting,
        create_teacher_outline_setting,
        export_teacher_course_package,
        export_teacher_slide,
        format_teacher_courseware_quiz_question,
        generate_teacher_courseware_quiz_subjects,
        log_teacher_activity_read,
        leave_teacher_resource_group,
        publish_teacher_activities,
        publish_teacher_shared_resource,
        save_teacher_activity_resource,
        save_teacher_classroom_subjects,
        save_teacher_course_package,
        save_teacher_shared_resource,
        score_teacher_classroom,
        score_teacher_custom_item,
        score_teacher_exam,
        score_teacher_forum,
        sort_teacher_outline_setting,
        sort_teacher_module_activities,
        sort_teacher_modules,
        sort_teacher_syllabus_activities,
        sort_teacher_syllabuses,
        start_teacher_rollcall,
        stop_teacher_number_rollcall,
        stop_teacher_qr_rollcall,
        stop_teacher_radar_rollcall,
        stop_teacher_rollcall,
        stop_teacher_timetable_rollcall,
        sync_teacher_courses_from_urp,
        submit_teacher_edu_scores,
        mark_teacher_bulletin_read,
        toggle_teacher_outline_setting,
        teacher_api_request,
        teacher_activity_specs,
        teacher_classroom_specs,
        teacher_endpoint_specs,
        teacher_exam_specs,
        teacher_group_set_specs,
        teacher_questionnaire_specs,
        teacher_rollcall_detail_specs,
        random_teacher_grouping,
        update_teacher_announce_score_settings,
        update_teacher_activity,
        update_teacher_activity_comment,
        update_teacher_activity_comment_reply,
        update_teacher_activity_resource,
        update_teacher_air_credit_assignments,
        update_teacher_air_credit_course_usage_limit,
        update_teacher_air_credit_status,
        update_teacher_bulletin,
        update_teacher_calendar_meeting,
        update_teacher_classroom_exam,
        update_teacher_classroom_status,
        update_teacher_classroom_subject_status,
        update_teacher_course_package,
        update_teacher_courseware_quiz_subjects,
        update_teacher_custom_score_item,
        update_teacher_course_estimate,
        update_teacher_enrollment_scores,
        update_teacher_exam,
        update_teacher_group,
        update_teacher_group_info,
        update_teacher_group_member,
        update_teacher_group_members,
        update_teacher_group_set,
        update_teacher_homework_announce_status,
        update_teacher_homework_rubric,
        update_teacher_chinamcloud_resources,
        update_teacher_course_outline,
        update_teacher_rollcall,
        update_teacher_radar_rollcall_position,
        update_teacher_enrollment_role,
        update_teacher_enrollments_role,
        update_teacher_forum_status,
        update_teacher_entry,
        update_teacher_outline_required_options,
        update_teacher_outline_setting,
        update_teacher_questionnaire_subject,
        update_teacher_resource_group,
        update_teacher_resource_group_resource,
        update_teacher_subject_lib,
        set_teacher_shared_resource_collection,
        update_teacher_slide,
        update_teacher_slide_video_info,
        update_teacher_module,
        update_teacher_merged_rollcall_students,
        update_teacher_rollcall_score,
        update_teacher_rollcall_setting,
        update_teacher_student_rollcalls,
        update_teacher_rubric,
        update_teacher_score_book,
        update_teacher_score_publish_item_maps,
        update_teacher_score_type_settings,
        update_teacher_syllabus,
        update_teacher_teaching_calendar,
        update_teacher_total_scores,
        comment_teacher_exam_status,
        delete_teacher_enrollment,
        delete_teacher_enrollments,
        sort_teacher_groups,
    )
    from troTHU.tron_http import (
        LOGIN_URL,
        TRON,
        LoginPageChangedError,
        LoginRejectedError,
        TronHttpClient,
        TronHttpError,
        UnauthorizedError,
        UnexpectedResponseError,
        default_endpoints,
        endpoints_from_provider,
        extract_login_form as extract_login_form_data,
        has_session_cookie as has_session_cookie_data,
    )
    from troTHU.rollcall_models import (
        AttendanceType,
        NotificationEvent,
        RollcallAction,
        RollcallDecision,
    )
    from troTHU.rollcall_engine import (
        classify_rollcall as engine_classify_rollcall,
        decide_rollcall as engine_decide_rollcall,
        select_rollcall as engine_select_rollcall,
    )
    from troTHU.runtime_helpers import (
        BIG_DIGITS,
        RadarCoordinateResult,
        TIME_RANGE_PATTERN,
        build_number_progress_message,
        build_radar_signal,
        coerce_bool,
        coerce_positive_float,
        coerce_positive_int,
        format_found_code_banner,
        format_time_value,
        is_within_any_schedule,
        is_within_schedule,
        make_payload_excerpt,
        normalize_radar_boundary_points as runtime_normalize_radar_boundary_points,
        normalize_schedule_range,
        normalize_schedule_ranges,
        normalize_text,
        parse_radar_answer_result,
        parse_schedule_range,
        parse_schedule_ranges,
        parse_time_value,
        render_big_digits,
    )
    from troTHU.ux_tools import (
        check_item,
        export_debug_bundle,
        file_age_seconds,
        human_age,
        json_text,
        render_check_items,
        summarize_logs,
        tail_log_records,
    )
except ImportError:
    from account_store import (
        clear_session_cookies,
        cookie_cache_enabled,
        cookie_path,
        get_active_profile,
        get_keyring_password,
        keyring_available,
        list_profiles,
        load_session_cookies,
        normalize_accounts_config,
        normalize_profile_name,
        remove_profile,
        save_session_cookies,
        set_keyring_password,
        set_profile,
        switch_profile,
    )
    from account_runtime_store import (
        load_runtime_state,
        mark_check_result,
        mark_login_result,
        mark_monitor_state,
        mark_profile_error,
        runtime_profile_summary,
        runtime_state_path,
    )
    from adapter_bridge import (
        AdapterBinding,
        binding_key,
        map_adapter_command,
    )
    from app_blueprint import (
        build_app_blueprint,
        format_app_blueprint_summary,
        validate_app_blueprint,
    )
    from app_shell import run_app_shell
    from app_shell_polish import (
        build_shell_action_catalog,
        build_shell_drilldown,
        build_shell_ui_model,
    )
    from bot_runtime import normalize_admins_config
    from connection_probe import (
        run_connection_probe,
        sanitize_probe_url,
    )
    from course_discovery import (
        CourseDiscoveryError,
        discover_courses,
    )
    from local_scanner import run_scanner_server
    from notification_bus import dispatch_notification_event
    from notification_delivery import (
        NotificationRequest,
        NotificationSendError,
        build_notification_requests as build_notification_requests_from_config,
        normalize_telegram_bot_key,
        send_notification_request,
    )
    from observability import (
        build_observability_snapshot,
        classify_recent_events,
        format_dashboard_snapshot,
        format_log_summary,
    )
    from package_diagnostics import build_package_diagnostic_report
    from provider_ready_gate import (
        build_provider_ready_gate,
        format_provider_ready_gate,
    )
    from provider_verification import (
        build_provider_fixture_template,
        build_provider_verification_checklist,
        summarize_provider_verification,
        validate_provider_fixture,
    )
    from provider_fixture_review import (
        build_provider_fixture_review,
        build_provider_fixture_review_template,
        format_provider_fixture_review,
        review_provider_fixture_dir,
        review_provider_fixture_file,
    )
    from pending_qr import (
        DEFAULT_PENDING_QR_PROVIDER,
        add_pending_qr,
        list_pending_qr,
        match_pending_qr,
        remove_pending_qr,
    )
    from qr_rollcall import (
        QrCodeData,
        answer_qr_rollcall,
        parse_qr_payload,
        parse_qr_payload_with_diagnostics,
    )
    from number_rollcall import (
        NumberAttemptStatus,
        NumberCodeLookup,
        classify_number_response,
        coerce_number_code,
        parse_number_code_payload,
    )
    from providers import (
        DEFAULT_PROVIDER,
        get_provider,
        list_all_providers,
        list_supported_providers,
        normalize_provider_config,
        provider_support_report,
        provider_registry_config,
        tronclass_api_endpoints,
    )
    from research_mode import normalize_research_mode_config
    from research_sandbox import (
        ResearchCaptureError,
        ResearchGateError,
        append_research_capture,
        build_browser_capture_metadata,
        build_research_status,
        capture_browser_target_metadata,
        capture_research_api_target,
        capture_rollcall_probe,
        capture_student_rollcalls_probe,
        ensure_research_allowed,
    )
    from webview_sync import (
        WebViewSyncError,
        build_webview_cookie_preview,
        build_webview_sync_status,
        import_webview_cookies,
        parse_webview_cookie_export,
    )
    from debug_capture import append_debug_capture
    from radar_solver import (
        DEFAULT_BOUNDARY_POINTS,
        DistanceObservation,
        GeoPoint,
        RadarGeometryError,
        build_probe_plan,
        choose_fourth_probe,
        final_candidate_points,
        solve_position,
    )
    from radar_rollcall import (
        build_radar_answer_payload,
        build_radar_attempt_diagnostic,
        parse_radar_lite_payload,
    )
    from radar_map_assist import build_radar_map_assist
    from release_checklist import (
        build_release_build_plan,
        build_release_checklist,
        format_release_checklist,
    )
    from release_builder import (
        format_release_build_summary,
        run_release_build_pipeline,
    )
    from real_validation import (
        append_local_smoke_validation_records,
        append_real_validation_record,
        build_local_smoke_validation_records,
        build_real_validation_checklist,
        format_real_validation_summary,
        run_local_validation_smoke,
        summarize_real_validation,
    )
    from discord_adapter import sync_discord_command_schema
    from discord_gateway import build_gateway_health, run_discord_gateway
    from teacher_runtime import (
        TEACHER_ENDPOINT_GROUPS,
        TeacherDiscoveryError,
        build_teacher_activity_report,
        build_teacher_classroom_report,
        build_teacher_course_report,
        build_teacher_exam_report,
        build_teacher_group_set_report,
        build_teacher_questionnaire_report,
        build_teacher_rollcall_report,
        activate_teacher_rollcall,
        add_teacher_activity_comment,
        answer_teacher_number_rollcall,
        answer_teacher_qr_rollcall,
        answer_teacher_radar_rollcall,
        cancel_recommend_teacher_submission,
        check_teacher_activity_dependents,
        check_teacher_module_dependents,
        check_teacher_syllabus_dependents,
        classify_account_type,
        classify_teacher_course,
        clear_teacher_air_credit_remaining_credits,
        copy_teacher_group_set,
        create_teacher_course_estimate,
        create_teacher_course_estimate_reply,
        create_teacher_activity,
        create_teacher_air_credit_assignments,
        create_teacher_bulletin,
        create_teacher_classroom_exam,
        create_teacher_course_package,
        create_teacher_group,
        create_teacher_group_set,
        create_teacher_courseware_quiz_subjects,
        create_teacher_module,
        create_teacher_merged_rollcall,
        create_teacher_module_rollcall,
        create_teacher_syllabus,
        create_teacher_custom_score_item,
        create_teacher_exam,
        create_teacher_rollcall,
        create_teacher_rubric,
        create_teacher_questionnaire_subject,
        create_teacher_subject_lib,
        create_teacher_teaching_calendar,
        delete_teacher_bulletin,
        delete_teacher_classroom,
        delete_teacher_classroom_subjects,
        delete_teacher_course_package,
        delete_teacher_course_estimate,
        delete_teacher_course_estimate_reply,
        delete_teacher_activity,
        delete_teacher_activity_comment,
        delete_teacher_activity_comment_reply,
        delete_teacher_activity_resource,
        delete_teacher_questionnaire_subject,
        delete_teacher_subject_lib,
        delete_teacher_subject_lib_subjects,
        delete_teacher_group,
        delete_teacher_group_member,
        delete_teacher_group_set,
        delete_teacher_module,
        delete_teacher_rollcall,
        delete_teacher_activities,
        delete_teacher_calendar_meeting,
        delete_teacher_custom_score_item,
        delete_teacher_exams,
        delete_teacher_rubrics,
        delete_teacher_syllabus,
        delete_teacher_teaching_calendar,
        delete_teacher_outline_setting_option,
        discover_teacher_context,
        download_teacher_api_path,
        download_teacher_api_request,
        download_teacher_qrcode,
        download_teacher_air_credit_stats_export,
        download_teacher_category_topics_export,
        download_teacher_cloud_classroom_live_classes_export,
        download_teacher_course_stat_students_export,
        download_teacher_ai_ppt_user_usage_export,
        download_teacher_department_attendance_export,
        download_teacher_department_user_attendance_export,
        download_teacher_management_calendar_meeting_export,
        download_teacher_questionnaire_export,
        download_teacher_shared_resource_blob,
        download_teacher_shared_resource_stat_export,
        download_teacher_shared_resource_subject_lib_export,
        download_teacher_shared_resource_video_stat_export,
        download_teacher_stat_attendance_export_to,
        download_teacher_stat_courses_export_to,
        download_teacher_stat_vtrses_data_export,
        download_teacher_stat_report_export,
        download_teacher_tencent_meeting_statistics_export,
        download_teacher_topic_export,
        download_teacher_third_part_upload,
        download_teacher_upload_blob,
        download_teacher_upload_modified_image,
        download_teacher_upload_reference_blob,
        download_teacher_upload_swf,
        download_teacher_upload_thumbnail,
        download_teacher_wedrive_file,
        upload_teacher_file,
        fetch_teacher_api_path,
        fetch_teacher_activity_uploads_license,
        fetch_teacher_ai_ppt_report,
        fetch_teacher_air_credit_report,
        fetch_teacher_authoring_report,
        fetch_teacher_calendar_meetings,
        fetch_teacher_completion_criteria,
        fetch_teacher_catalog_report,
        fetch_teacher_course_estimate_replies,
        fetch_teacher_course_estimate_user,
        fetch_teacher_course_package_course,
        fetch_teacher_course_completion_criteria,
        fetch_teacher_course_rollcall_detail,
        fetch_teacher_courseware_quizzes,
        fetch_teacher_courseware_quiz_settings,
        fetch_teacher_courseware_quiz_subjects,
        fetch_teacher_course_statistics,
        fetch_teacher_department_report,
        fetch_teacher_endpoint,
        fetch_teacher_forum_categories,
        fetch_teacher_forum_category,
        fetch_teacher_management_calendar_meetings,
        fetch_teacher_media_report,
        fetch_teacher_org_bulletin_report,
        fetch_teacher_platform_report,
        fetch_teacher_questionnaire_submissions,
        fetch_teacher_rollcall_endpoint,
        fetch_teacher_rollcall_count,
        fetch_teacher_rollcall_status_result,
        fetch_teacher_rollcall_students_page,
        fetch_teacher_ongoing_student_rollcalls,
        fetch_teacher_leave_record,
        fetch_teacher_student_rollcalls,
        fetch_teacher_subject_lib_folders,
        fetch_teacher_subject_lib_knowledge_nodes,
        fetch_teacher_subject_lib_statistic,
        fetch_teacher_subject_lib_subjects,
        fetch_teacher_subject_libs,
        fetch_teacher_teaching_calendars,
        fetch_teacher_vtrs_report,
        grade_teacher_rollcalls,
        grade_teacher_submission,
        import_teacher_course_groups,
        import_teacher_course_package,
        import_teacher_enrollments,
        import_teacher_item_scores,
        import_teacher_questionnaire_subjects,
        import_teacher_rollcalls,
        import_teacher_scores,
        import_teacher_seat_numbers,
        move_teacher_subject_lib_subjects,
        move_teacher_subject_libs,
        notify_teacher_outline_editing,
        operate_teacher_activity_comments,
        recommend_teacher_submissions,
        reply_teacher_activity_comment,
        resort_teacher_activity,
        copy_teacher_subject_libs_to_courseware_quiz,
        copy_teacher_subject_lib,
        copy_teacher_subject_libs_to_user,
        create_teacher_calendar_meeting,
        create_teacher_outline_setting,
        export_teacher_course_package,
        format_teacher_courseware_quiz_question,
        generate_teacher_courseware_quiz_subjects,
        log_teacher_activity_read,
        publish_teacher_activities,
        save_teacher_activity_resource,
        save_teacher_classroom_subjects,
        save_teacher_course_package,
        score_teacher_classroom,
        score_teacher_custom_item,
        score_teacher_exam,
        score_teacher_forum,
        sort_teacher_outline_setting,
        sort_teacher_module_activities,
        sort_teacher_modules,
        sort_teacher_syllabus_activities,
        sort_teacher_syllabuses,
        start_teacher_rollcall,
        stop_teacher_number_rollcall,
        stop_teacher_qr_rollcall,
        stop_teacher_radar_rollcall,
        stop_teacher_rollcall,
        stop_teacher_timetable_rollcall,
        sync_teacher_courses_from_urp,
        submit_teacher_edu_scores,
        mark_teacher_bulletin_read,
        toggle_teacher_outline_setting,
        teacher_api_request,
        teacher_activity_specs,
        teacher_classroom_specs,
        teacher_endpoint_specs,
        teacher_exam_specs,
        teacher_group_set_specs,
        teacher_questionnaire_specs,
        teacher_rollcall_detail_specs,
        random_teacher_grouping,
        update_teacher_announce_score_settings,
        update_teacher_activity,
        update_teacher_activity_comment,
        update_teacher_activity_comment_reply,
        update_teacher_activity_resource,
        update_teacher_air_credit_assignments,
        update_teacher_air_credit_course_usage_limit,
        update_teacher_air_credit_status,
        update_teacher_bulletin,
        update_teacher_calendar_meeting,
        update_teacher_classroom_exam,
        update_teacher_classroom_status,
        update_teacher_classroom_subject_status,
        update_teacher_course_package,
        update_teacher_courseware_quiz_subjects,
        update_teacher_custom_score_item,
        update_teacher_course_estimate,
        update_teacher_enrollment_scores,
        update_teacher_exam,
        update_teacher_group,
        update_teacher_group_info,
        update_teacher_group_member,
        update_teacher_group_members,
        update_teacher_group_set,
        update_teacher_homework_announce_status,
        update_teacher_homework_rubric,
        update_teacher_chinamcloud_resources,
        update_teacher_course_outline,
        update_teacher_rollcall,
        update_teacher_radar_rollcall_position,
        update_teacher_enrollment_role,
        update_teacher_enrollments_role,
        update_teacher_forum_status,
        update_teacher_outline_required_options,
        update_teacher_outline_setting,
        update_teacher_questionnaire_subject,
        update_teacher_subject_lib,
        update_teacher_module,
        update_teacher_merged_rollcall_students,
        update_teacher_rollcall_score,
        update_teacher_rollcall_setting,
        update_teacher_student_rollcalls,
        update_teacher_rubric,
        update_teacher_score_book,
        update_teacher_score_publish_item_maps,
        update_teacher_score_type_settings,
        update_teacher_syllabus,
        update_teacher_teaching_calendar,
        update_teacher_total_scores,
        comment_teacher_exam_status,
        delete_teacher_enrollment,
        delete_teacher_enrollments,
        sort_teacher_groups,
    )
    from tron_http import (
        LOGIN_URL,
        TRON,
        LoginPageChangedError,
        LoginRejectedError,
        TronHttpClient,
        TronHttpError,
        UnauthorizedError,
        UnexpectedResponseError,
        default_endpoints,
        endpoints_from_provider,
        extract_login_form as extract_login_form_data,
        has_session_cookie as has_session_cookie_data,
    )
    from rollcall_models import (
        AttendanceType,
        NotificationEvent,
        RollcallAction,
        RollcallDecision,
    )
    from rollcall_engine import (
        classify_rollcall as engine_classify_rollcall,
        decide_rollcall as engine_decide_rollcall,
        select_rollcall as engine_select_rollcall,
    )
    from runtime_helpers import (
        BIG_DIGITS,
        RadarCoordinateResult,
        TIME_RANGE_PATTERN,
        build_number_progress_message,
        build_radar_signal,
        coerce_bool,
        coerce_positive_float,
        coerce_positive_int,
        format_found_code_banner,
        format_time_value,
        is_within_any_schedule,
        is_within_schedule,
        make_payload_excerpt,
        normalize_radar_boundary_points as runtime_normalize_radar_boundary_points,
        normalize_schedule_range,
        normalize_schedule_ranges,
        normalize_text,
        parse_radar_answer_result,
        parse_schedule_range,
        parse_schedule_ranges,
        parse_time_value,
        render_big_digits,
    )
    from ux_tools import (
        check_item,
        export_debug_bundle,
        file_age_seconds,
        human_age,
        json_text,
        render_check_items,
        summarize_logs,
        tail_log_records,
    )

CURRENT_PROMPT = "切換學號 (輸入 exit 離開) > "

PROMPT_INPUT_ACTIVE = False

CONSOLE_DEFERRED_LINES: List[str] = []

LAST_STATUS = "初始化中"

NUMBER_CODE_LIMIT = 10000

NUMBER_WORKER_COUNT = 100

NUMBER_MIN_WORKER_COUNT = 5

NUMBER_REQUEST_RETRIES = 3

NUMBER_PROGRESS_INTERVAL = 0.5

NUMBER_COOLDOWN_SECONDS = 5.0

NUMBER_MAX_COOLDOWNS = 3

NUMBER_TRANSIENT_FAILURE_THRESHOLD = 20

NUMBER_TRANSIENT_FAILURE_RATIO = 0.35

DEFAULT_OPERATING_RANGE = ["00:00", "00:00"]

LOGIN_RETRY_DELAYS = (10.0, 30.0, 60.0, 300.0)

FATAL_NOTIFICATION_INTERVAL = 300.0

DEFAULT_HTTP_TIMEOUT_SECONDS = 20.0

DEFAULT_NOTIFICATION_TIMEOUT_SECONDS = 10.0

PLACEHOLDER_CREDENTIAL_VALUES = {
    "",
    "YOUR_STUDENT_ID",
    "YOUR_PASSWORD",
    "您的學號",
    "您的密碼",
}

DEFAULT_USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36 Edge/136.0.0.0",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/109.0.5410.0 Safari/537.36",
    "Mozilla/5.0 (Android 10; Mobile; rv:78.0) Gecko/20100101 Firefox/78.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:83.0) Gecko/20100101 Firefox/83.0",
]

DEFAULT_CONFIG = {
    "account": {
        "user": "YOUR_STUDENT_ID",
        "passwd": "YOUR_PASSWORD",
    },
    "accounts": {
        "current": "default",
        "profiles": {
            "default": {
                "user": "YOUR_STUDENT_ID",
                "passwd": "YOUR_PASSWORD",
                "label": "legacy config",
                "school": "thu",
            },
        },
    },
    "provider": provider_registry_config(),
    "session": {
        "cache_cookies": True,
    },
    "auth": {
        "browser_assisted_login": {
            "enabled": False,
            "headless": True,
            "timeout_ms": 45000,
        },
    },
    "ux": {
        "pending_qr_ttl_seconds": 600,
        "debug_bundle_log_limit": 50,
    },
    "local_ui": {
        "host": "127.0.0.1",
        "port": 8765,
    },
    "webview": {
        "cookie_sync": {
            "enabled": False,
            "allow_cookie_import": False,
            "allowed_domains": [],
            "cookie_name_allowlist": ["session"],
            "allow_experimental_provider": False,
        },
    },
    "integrations": {
        "discord": {
            "enable": False,
            "token_env": "DISCORD_BOT_TOKEN",
            "channel_env": "DISCORD_CHANNEL_ID",
            "public_key_env": "DISCORD_PUBLIC_KEY",
            "application_id_env": "DISCORD_APPLICATION_ID",
            "guild_id_env": "DISCORD_GUILD_ID",
            "ephemeral_replies": True,
        },
        "line": {
            "enable": False,
            "token_env": "LINE_CHANNEL_ACCESS_TOKEN",
            "secret_env": "LINE_CHANNEL_SECRET",
        },
        "telegram": {
            "enable": False,
            "token_env": "TELEGRAM_BOT_TOKEN",
            "chat_env": "TELEGRAM_CHAT_ID",
        },
        "admins": {
            "discord": [],
            "line": [],
        },
        "security": {
            "allowed_channels": {
                "discord": [],
                "line": [],
            },
            "dangerous_cooldown_seconds": 30,
            "audit_log": True,
        },
        "bindings": {},
    },
    "notifications": {
        "tg": {
            "enable": False,
            "key": "",
            "chat": "",
        },
        "dc": {
            "enable": False,
            "key": "",
            "chat": "",
        },
    },
    "config": {
        "enable_log": True,
        "Senkaku": 1,
        "retries": 20,
        "http_timeout": DEFAULT_HTTP_TIMEOUT_SECONDS,
        "notification_timeout": DEFAULT_NOTIFICATION_TIMEOUT_SECONDS,
        "verify_ssl": True,
        "user-agent": list(DEFAULT_USER_AGENTS),
    },
    "time": {
        "timezone": "Asia/Taipei",
    },
    "number": {
        "concurrency": NUMBER_WORKER_COUNT,
        "min_concurrency": NUMBER_MIN_WORKER_COUNT,
        "request_retries": NUMBER_REQUEST_RETRIES,
        "cooldown_seconds": NUMBER_COOLDOWN_SECONDS,
        "max_cooldowns": NUMBER_MAX_COOLDOWNS,
        "transient_failure_threshold": NUMBER_TRANSIENT_FAILURE_THRESHOLD,
        "transient_failure_ratio": NUMBER_TRANSIENT_FAILURE_RATIO,
        "direct_code_lookup": {
            "enabled": True,
            "fallback_bruteforce": True,
        },
    },
    "radar": {
        "boundary_points": [[lat, lon] for lat, lon in DEFAULT_BOUNDARY_POINTS],
        "allow_outside_probe": True,
        "outside_scale": 1.6,
        "max_distance_probes": 4,
        "max_final_attempts": 100,
        "final_precision_min": 3,
        "final_precision_max": 14,
        "final_grid_step_meters": 5.0,
        "final_grid_radius_meters": 20.0,
    },
    "research": normalize_research_mode_config({}),
    "operating": {
        0: {"enable": True, "range": list(DEFAULT_OPERATING_RANGE)},
        1: {"enable": True, "range": list(DEFAULT_OPERATING_RANGE)},
        2: {"enable": True, "range": list(DEFAULT_OPERATING_RANGE)},
        3: {"enable": True, "range": list(DEFAULT_OPERATING_RANGE)},
        4: {"enable": True, "range": list(DEFAULT_OPERATING_RANGE)},
        5: {"enable": True, "range": list(DEFAULT_OPERATING_RANGE)},
        6: {"enable": True, "range": list(DEFAULT_OPERATING_RANGE)},
    },
}

YAML_ERROR_TYPES = tuple(
    error_type
    for error_type in (getattr(yaml, "YAMLError", None), ValueError)
    if isinstance(error_type, type) and issubclass(error_type, BaseException)
)

if getattr(sys, "frozen", False):
    BASE_DIR = Path(sys.executable).parent
else:
    BASE_DIR = Path(__file__).parent.parent

PATH = BASE_DIR / "log"

CONFIG_PATH = BASE_DIR / "config.yaml"
CONFIG_ADVANCED_PATH = BASE_DIR / "config.advanced.yaml"

RUNTIME_CREDENTIALS = {"user": "", "passwd": ""}

UNSUPPORTED_ROLLCALL_STATE = {"rollcall_id": None, "status": ""}

COMPLETED_NUMBER_ROLLCALLS: Dict[str, str] = {}

COMPLETED_RADAR_ROLLCALLS: Dict[str, bool] = {}

BOOTSTRAP_WARNINGS: List[str] = []

CONFIG_BOOTSTRAPPED = False

LAST_FATAL_NOTIFICATION_AT = 0.0

COOKIE_CACHE_RESTORED = False
CONFIG_WARNINGS: List[str] = []

@dataclass(frozen=True)
class LoginResult:
    status: str
    credential_source: str
    user: str = ""
    final_url: str = ""
    error: str = ""

    @property
    def ok(self) -> bool:
        return self.status == "success"

    @property
    def should_auto_retry(self) -> bool:
        return self.status in {"missing_session", "transient_error"}

LAST_LOGIN_RESULT = LoginResult(status="missing_credentials", credential_source="missing")

_LEGACY_EXPORTS = {
    '_app_shell_accounts': ('troTHU.cli_app', '_app_shell_accounts'),
    '_app_shell_drilldown': ('troTHU.cli_app', '_app_shell_drilldown'),
    '_app_shell_integrations': ('troTHU.cli_app', '_app_shell_integrations'),
    '_app_shell_logs_summary': ('troTHU.cli_app', '_app_shell_logs_summary'),
    '_app_shell_polish_reports': ('troTHU.cli_app', '_app_shell_polish_reports'),
    '_app_shell_provider_ready_gate': ('troTHU.cli_app', '_app_shell_provider_ready_gate'),
    '_app_shell_provider_verification': ('troTHU.cli_app', '_app_shell_provider_verification'),
    '_app_shell_release_check': ('troTHU.cli_app', '_app_shell_release_check'),
    '_app_shell_release_plan': ('troTHU.cli_app', '_app_shell_release_plan'),
    '_app_shell_snapshot': ('troTHU.cli_app', '_app_shell_snapshot'),
    '_app_shell_ui_model': ('troTHU.cli_app', '_app_shell_ui_model'),
    '_read_json_input': ('troTHU.cli_provider', '_read_json_input'),
    '_read_webview_cookie_input': ('troTHU.cli_app', '_read_webview_cookie_input'),
    '_research_gate_failure': ('troTHU.cli_research', '_research_gate_failure'),
    '_resolve_webview_profile': ('troTHU.cli_app', '_resolve_webview_profile'),
    '_send_notification': ('troTHU.logging_runtime', '_send_notification'),
    'account_doctor': ('troTHU.cli_accounts', 'account_doctor'),
    'account_runtime_summary': ('troTHU.status_reports', 'account_runtime_summary'),
    'account_show': ('troTHU.cli_accounts', 'account_show'),
    'account_state': ('troTHU.cli_accounts', 'account_state'),
    'account_state_report': ('troTHU.status_reports', 'account_state_report'),
    'app_blueprint_command': ('troTHU.cli_app', 'app_blueprint_command'),
    'app_main': ('troTHU.monitor_runtime', 'app_main'),
    'app_serve_command': ('troTHU.cli_app', 'app_serve_command'),
    'bind_account': ('troTHU.cli_accounts', 'bind_account'),
    'binding_summary': ('troTHU.status_reports', 'binding_summary'),
    'bootstrap_config': ('troTHU.config_runtime', 'bootstrap_config'),
    'bot_discord_gateway_command': ('troTHU.cli_bot', 'bot_discord_gateway_command'),
    'bot_discord_schema_command': ('troTHU.cli_bot', 'bot_discord_schema_command'),
    'bot_discord_sync_command': ('troTHU.cli_bot', 'bot_discord_sync_command'),
    'bot_serve_command': ('troTHU.cli_bot', 'bot_serve_command'),
    'build_arg_parser': ('troTHU.cli_parser', 'build_arg_parser'),
    'browser_assisted_login': ('troTHU.auth_runtime', 'browser_assisted_login'),
    'browser_assisted_login_available': ('troTHU.auth_runtime', 'browser_assisted_login_available'),
    'browser_assisted_login_status': ('troTHU.auth_runtime', 'browser_assisted_login_status'),
    'build_fatal_error_report': ('troTHU.logging_runtime', 'build_fatal_error_report'),
    'build_notification_requests': ('troTHU.logging_runtime', 'build_notification_requests'),
    'build_qr_preview': ('troTHU.qr_runtime', 'build_qr_preview'),
    'build_user_config': ('troTHU.config_view', 'build_user_config'),
    'check_rollcall': ('troTHU.rollcall_runtime', 'check_rollcall'),
    'classify_rollcall': ('troTHU.rollcall_runtime', 'classify_rollcall'),
    'clear_runtime_credentials': ('troTHU.config_runtime', 'clear_runtime_credentials'),
    'clone_session_cookies': ('troTHU.auth_runtime', 'clone_session_cookies'),
    'config_compact_command': ('troTHU.cli_system', 'config_compact_command'),
    'config_advanced_command': ('troTHU.cli_system', 'config_advanced_command'),
    'config_doctor_command': ('troTHU.cli_system', 'config_doctor_command'),
    'config_doctor_report': ('troTHU.config_view', 'config_doctor_report'),
    'config_show_command': ('troTHU.cli_system', 'config_show_command'),
    'config_summary': ('troTHU.cli_accounts', 'config_summary'),
    'config_view_summary': ('troTHU.config_view', 'config_view_summary'),
    'consume_bootstrap_warnings': ('troTHU.config_runtime', 'consume_bootstrap_warnings'),
    'cookie_report': ('troTHU.status_reports', 'cookie_report'),
    'course_discovery_report': ('troTHU.status_reports', 'course_discovery_report'),
    'courses_command': ('troTHU.cli_courses', 'courses_command'),
    'capture_realtime': ('troTHU.realtime_capture', 'capture_realtime'),
    'capture_rollcall_full': ('troTHU.rollcall_capture', 'capture_rollcall_full'),
    'append_rollcall_exchange': ('troTHU.rollcall_capture', 'append_rollcall_exchange'),
    'run_qr_data_probe': ('troTHU.qr_data_probe', 'run_qr_data_probe'),
    'run_qr_data_probe_for_rollcall': ('troTHU.rollcall_runtime', 'run_qr_data_probe_for_rollcall'),
    'qr_data_probe_autorun_enabled': ('troTHU.qr_data_probe', 'qr_data_probe_autorun_enabled'),
    'build_qr_data_probe_cases': ('troTHU.qr_data_probe', 'build_qr_data_probe_cases'),
    'derive_qr_timestamp_from_server_time': ('troTHU.qr_data_probe', 'derive_qr_timestamp_from_server_time'),
    'extract_rollcall_time_value': ('troTHU.qr_data_probe', 'extract_rollcall_time_value'),
    'qr_data_probe_command': ('troTHU.cli_qr', 'qr_data_probe_command'),
    'capture_rollcall_probe': ('troTHU.research_sandbox', 'capture_rollcall_probe'),
    'capture_student_rollcalls_probe': ('troTHU.research_sandbox', 'capture_student_rollcalls_probe'),
    'validate_probe_target': ('troTHU.research_sandbox', 'validate_probe_target'),
    'RISKY_PROBE_TARGETS': ('troTHU.research_sandbox', 'RISKY_PROBE_TARGETS'),
    'PROBE_TARGETS_NEED_ROLLCALL_ID': ('troTHU.research_sandbox', 'PROBE_TARGETS_NEED_ROLLCALL_ID'),
    'create_client_timeout': ('troTHU.auth_runtime', 'create_client_timeout'),
    'create_http_client_timeout': ('troTHU.auth_runtime', 'create_http_client_timeout'),
    'create_http_connector': ('troTHU.auth_runtime', 'create_http_connector'),
    'create_notification_timeout': ('troTHU.auth_runtime', 'create_notification_timeout'),
    'create_tron_http_client': ('troTHU.auth_runtime', 'create_tron_http_client'),
    'credential_report': ('troTHU.status_reports', 'credential_report'),
    'current_datetime': ('troTHU.config_runtime', 'current_datetime'),
    'daily_log_path': ('troTHU.logging_runtime', 'daily_log_path'),
    'dashboard_command': ('troTHU.cli_system', 'dashboard_command'),
    'debug_capture_command': ('troTHU.cli_research', 'debug_capture_command'),
    'decide_rollcall': ('troTHU.rollcall_runtime', 'decide_rollcall'),
    'decode_qr_image_file': ('troTHU.qr_runtime', 'decode_qr_image_file'),
    'doctor': ('troTHU.status_reports', 'doctor'),
    'doctor_report': ('troTHU.status_reports', 'doctor_report'),
    'enable_insecure_ssl_fallback': ('troTHU.auth_runtime', 'enable_insecure_ssl_fallback'),
    'ensure_config_exists': ('troTHU.config_runtime', 'ensure_config_exists'),
    'extract_login_form': ('troTHU.auth_runtime', 'extract_login_form'),
    'fallback_to_browser_assisted_login': ('troTHU.auth_runtime', 'fallback_to_browser_assisted_login'),
    'find_profile': ('troTHU.status_reports', 'find_profile'),
    'format_config_doctor': ('troTHU.config_view', 'format_config_doctor'),
    'get_active_http_endpoints': ('troTHU.status_reports', 'get_active_http_endpoints'),
    'get_active_provider_config': ('troTHU.status_reports', 'get_active_provider_config'),
    'get_active_provider_definition': ('troTHU.status_reports', 'get_active_provider_definition'),
    'get_active_provider_key': ('troTHU.status_reports', 'get_active_provider_key'),
    'get_browser_assisted_login_config': ('troTHU.auth_runtime', 'get_browser_assisted_login_config'),
    'get_config_timezone': ('troTHU.config_runtime', 'get_config_timezone'),
    'get_config_timezone_name': ('troTHU.config_runtime', 'get_config_timezone_name'),
    'get_environment_credentials': ('troTHU.config_runtime', 'get_environment_credentials'),
    'get_http_timeout_seconds': ('troTHU.auth_runtime', 'get_http_timeout_seconds'),
    'get_login_retry_delay': ('troTHU.auth_runtime', 'get_login_retry_delay'),
    'get_notification_timeout_seconds': ('troTHU.auth_runtime', 'get_notification_timeout_seconds'),
    'get_number_config': ('troTHU.config_runtime', 'get_number_config'),
    'get_poll_interval': ('troTHU.config_runtime', 'get_poll_interval'),
    'get_retry_limit': ('troTHU.config_runtime', 'get_retry_limit'),
    'get_runtime_credentials': ('troTHU.config_runtime', 'get_runtime_credentials'),
    'get_schedule_for_day': ('troTHU.config_runtime', 'get_schedule_for_day'),
    'get_session_id_header': ('troTHU.auth_runtime', 'get_session_id_header'),
    'get_ssl_request_setting': ('troTHU.auth_runtime', 'get_ssl_request_setting'),
    'get_verify_ssl': ('troTHU.auth_runtime', 'get_verify_ssl'),
    'handle_account_command': ('troTHU.cli_accounts', 'handle_account_command'),
    'has_real_credential': ('troTHU.config_runtime', 'has_real_credential'),
    'has_session_cookie': ('troTHU.auth_runtime', 'has_session_cookie'),
    'init_command': ('troTHU.cli_system', 'init_command'),
    'integration_report': ('troTHU.status_reports', 'integration_report'),
    'is_completed_number_rollcall': ('troTHU.rollcall_runtime', 'is_completed_number_rollcall'),
    'is_placeholder_credential': ('troTHU.config_runtime', 'is_placeholder_credential'),
    'is_ssl_certificate_verification_error': ('troTHU.auth_runtime', 'is_ssl_certificate_verification_error'),
    'load_config': ('troTHU.config_runtime', 'load_config'),
    'load_advanced_config': ('troTHU.config_runtime', 'load_advanced_config'),
    'log': ('troTHU.logging_runtime', 'log'),
    'log_print': ('troTHU.logging_runtime', 'log_print'),
    'flush_console_output': ('troTHU.logging_runtime', 'flush_console_output'),
    'login': ('troTHU.auth_runtime', 'login'),
    'login_test_command': ('troTHU.cli_courses', 'login_test_command'),
    'logs_command': ('troTHU.cli_system', 'logs_command'),
    'main': ('troTHU.cli_main', 'main'),
    'make_config_backup_path': ('troTHU.config_runtime', 'make_config_backup_path'),
    'mark_completed_number_rollcall': ('troTHU.rollcall_runtime', 'mark_completed_number_rollcall'),
    'maybe_notify_unsupported_rollcall': ('troTHU.rollcall_runtime', 'maybe_notify_unsupported_rollcall'),
    'mes': ('troTHU.logging_runtime', 'mes'),
    'module_available': ('troTHU.status_reports', 'module_available'),
    'monitor_loop': ('troTHU.monitor_runtime', 'monitor_loop'),
    'normalize_config': ('troTHU.config_runtime', 'normalize_config'),
    'normalize_radar_boundary_points': ('troTHU.config_runtime', 'normalize_radar_boundary_points'),
    'list_all_providers': ('troTHU.providers', 'list_all_providers'),
    'notification_report': ('troTHU.status_reports', 'notification_report'),
    'notify_event': ('troTHU.logging_runtime', 'notify_event'),
    'number': ('troTHU.number_runtime', 'number'),
    'number_log_path': ('troTHU.logging_runtime', 'number_log_path'),
    'number_rollcall_key': ('troTHU.rollcall_runtime', 'number_rollcall_key'),
    'package_check': ('troTHU.cli_system', 'package_check'),
    'pending_qr_summary': ('troTHU.status_reports', 'pending_qr_summary'),
    'print_pending_qr': ('troTHU.qr_runtime', 'print_pending_qr'),
    'print_qr_preview': ('troTHU.qr_runtime', 'print_qr_preview'),
    'print_status': ('troTHU.status_reports', 'print_status'),
    'parse_simple_config_text': ('troTHU.simple_config', 'parse_simple_config_text'),
    'provider_block_message': ('troTHU.status_reports', 'provider_block_message'),
    'provider_fixture_review_command': ('troTHU.cli_provider', 'provider_fixture_review_command'),
    'provider_fixture_review_dir_command': ('troTHU.cli_provider', 'provider_fixture_review_dir_command'),
    'provider_fixture_review_template_command': ('troTHU.cli_provider', 'provider_fixture_review_template_command'),
    'provider_fixture_template_command': ('troTHU.cli_provider', 'provider_fixture_template_command'),
    'provider_fixture_validate_command': ('troTHU.cli_provider', 'provider_fixture_validate_command'),
    'provider_guard_result': ('troTHU.status_reports', 'provider_guard_result'),
    'provider_is_daily_allowed': ('troTHU.status_reports', 'provider_is_daily_allowed'),
    'provider_list_command': ('troTHU.cli_provider', 'provider_list_command'),
    'provider_prefers_browser_assisted_login': ('troTHU.auth_runtime', 'provider_prefers_browser_assisted_login'),
    'provider_ready_gate_command': ('troTHU.cli_provider', 'provider_ready_gate_command'),
    'provider_requires_manual_cookie_login': ('troTHU.auth_runtime', 'provider_requires_manual_cookie_login'),
    'provider_report': ('troTHU.status_reports', 'provider_report'),
    'provider_show_command': ('troTHU.cli_provider', 'provider_show_command'),
    'provider_summary': ('troTHU.cli_provider', 'provider_summary'),
    'provider_verify_checklist_command': ('troTHU.cli_provider', 'provider_verify_checklist_command'),
    'QrInfoCaptureOptions': ('troTHU.qr_info_capture', 'QrInfoCaptureOptions'),
    'analyze_qr_observation': ('troTHU.qr_info_capture', 'analyze_qr_observation'),
    'build_qr_info_capture_options_for_rollcall': ('troTHU.qr_info_capture', 'build_qr_info_capture_options_for_rollcall'),
    'build_qr_info_capture_targets': ('troTHU.qr_info_capture', 'build_qr_info_capture_targets'),
    'qr_info_capture_enabled': ('troTHU.qr_info_capture', 'qr_info_capture_enabled'),
    'qr_command': ('troTHU.cli_qr', 'qr_command'),
    'qr_fanout_command': ('troTHU.qr_runtime', 'qr_fanout_command'),
    'qr_fanout_result': ('troTHU.qr_runtime', 'qr_fanout_result'),
    'qr_image_command': ('troTHU.qr_runtime', 'qr_image_command'),
    'qr_paste_command': ('troTHU.qr_runtime', 'qr_paste_command'),
    'qr_scanner_submit': ('troTHU.qr_runtime', 'qr_scanner_submit'),
    'run_qr_info_capture': ('troTHU.qr_info_capture', 'run_qr_info_capture'),
    'radar': ('troTHU.radar_runtime', 'radar'),
    'random_id': ('troTHU.auth_runtime', 'random_id'),
    'random_ua': ('troTHU.auth_runtime', 'random_ua'),
    'masked_login_user': ('troTHU.auth_runtime', 'masked_login_user'),
    'record_check_runtime': ('troTHU.rollcall_runtime', 'record_check_runtime'),
    'run_full_rollcall_capture': ('troTHU.rollcall_runtime', 'run_full_rollcall_capture'),
    'run_qr_info_capture_for_rollcall': ('troTHU.rollcall_runtime', 'run_qr_info_capture_for_rollcall'),
    'run_realtime_capture': ('troTHU.rollcall_runtime', 'run_realtime_capture'),
    'try_clipboard_qr_autosubmit': ('troTHU.rollcall_runtime', 'try_clipboard_qr_autosubmit'),
    'read_clipboard_qr_payload': ('troTHU.clipboard_qr', 'read_clipboard_qr_payload'),
    'clipboard_autosubmit_enabled': ('troTHU.clipboard_qr', 'clipboard_autosubmit_enabled'),
    'report_rollcall_progress': ('troTHU.rollcall_progress', 'report_rollcall_progress'),
    'fetch_rollcall_progress': ('troTHU.rollcall_progress', 'fetch_rollcall_progress'),
    'summarize_rollcall_progress': ('troTHU.rollcall_progress', 'summarize_rollcall_progress'),
    'record_login_runtime': ('troTHU.auth_runtime', 'record_login_runtime'),
    'record_monitor_runtime': ('troTHU.monitor_runtime', 'record_monitor_runtime'),
    'record_runtime_error': ('troTHU.rollcall_runtime', 'record_runtime_error'),
    'release_build_command': ('troTHU.cli_system', 'release_build_command'),
    'release_check_command': ('troTHU.cli_system', 'release_check_command'),
    'report_fatal_exception': ('troTHU.logging_runtime', 'report_fatal_exception'),
    'render_compact_config': ('troTHU.config_view', 'render_compact_config'),
    'render_simple_config': ('troTHU.simple_config', 'render_simple_config'),
    'research_api_command': ('troTHU.cli_research', 'research_api_command'),
    'research_browser_capture_command': ('troTHU.cli_research', 'research_browser_capture_command'),
    'research_browser_check_command': ('troTHU.cli_research', 'research_browser_check_command'),
    'research_probe_command': ('troTHU.cli_research', 'research_probe_command'),
    'research_report': ('troTHU.status_reports', 'research_report'),
    'research_status_command': ('troTHU.cli_research', 'research_status_command'),
    'redacted_login_user': ('troTHU.auth_runtime', 'redacted_login_user'),
    'run_connection_probe': ('troTHU.connection_probe', 'run_connection_probe'),
    'reset_unsupported_rollcall_state': ('troTHU.rollcall_runtime', 'reset_unsupported_rollcall_state'),
    'resolve_credentials': ('troTHU.config_runtime', 'resolve_credentials'),
    'merge_simple_and_advanced_config': ('troTHU.simple_config', 'merge_simple_and_advanced_config'),
    'split_normalized_config': ('troTHU.simple_config', 'split_normalized_config'),
    'is_simple_config_text': ('troTHU.simple_config', 'is_simple_config_text'),
    'infer_single_account_now': ('troTHU.simple_config', 'infer_single_account_now'),
    'open_config_in_legacy_notepad': ('troTHU.config_editor', 'open_config_in_legacy_notepad'),
    'ensure_config_now_or_open_editor': ('troTHU.config_editor', 'ensure_config_now_or_open_editor'),
    'reload_config_after_editor': ('troTHU.config_editor', 'reload_config_after_editor'),
    'watch_any_key_to_edit_config': ('troTHU.config_editor', 'watch_any_key_to_edit_config'),
    'config_now_value': ('troTHU.config_editor', 'config_now_value'),
    'effective_config_now_value': ('troTHU.config_editor', 'effective_config_now_value'),
    'resolve_now_target': ('troTHU.group_runtime', 'resolve_now_target'),
    'build_group_execution_plan': ('troTHU.group_runtime', 'build_group_execution_plan'),
    'submit_group_qr': ('troTHU.group_runtime', 'submit_group_qr'),
    'submit_group_number': ('troTHU.group_runtime', 'submit_group_number'),
    'submit_group_radar': ('troTHU.group_runtime', 'submit_group_radar'),
    'run_monitor_forever': ('troTHU.monitor_runtime', 'run_monitor_forever'),
    'save_account_for_next_launch': ('troTHU.config_runtime', 'save_account_for_next_launch'),
    'save_config': ('troTHU.config_runtime', 'save_config'),
    'sanitize_config_values': ('troTHU.input_safety', 'sanitize_config_values'),
    'sanitize_input_field': ('troTHU.input_safety', 'sanitize_input_field'),
    'sanitize_probe_url': ('troTHU.connection_probe', 'sanitize_probe_url'),
    'safe_qr_image_decode_report': ('troTHU.qr_runtime', 'safe_qr_image_decode_report'),
    'masked_password_input': ('troTHU.input_safety', 'masked_password_input'),
    'select_rollcall': ('troTHU.rollcall_runtime', 'select_rollcall'),
    'set_notification_sinks': ('troTHU.logging_runtime', 'set_notification_sinks'),
    'set_runtime_credentials': ('troTHU.config_runtime', 'set_runtime_credentials'),
    'should_auto_login_without_session': ('troTHU.auth_runtime', 'should_auto_login_without_session'),
    'should_try_browser_assisted_login': ('troTHU.auth_runtime', 'should_try_browser_assisted_login'),
    'sleep_or_shutdown': ('troTHU.monitor_runtime', 'sleep_or_shutdown'),
    'status_print': ('troTHU.logging_runtime', 'status_print'),
    'status_report': ('troTHU.status_reports', 'status_report'),
    'submit_qr_payload': ('troTHU.qr_runtime', 'submit_qr_payload'),
    'teacher_add_activity_comment_command': ('troTHU.cli_teacher', 'teacher_add_activity_comment_command'),
    'teacher_activities_command': ('troTHU.cli_teacher', 'teacher_activities_command'),
    'teacher_activity_command': ('troTHU.cli_teacher', 'teacher_activity_command'),
    'teacher_activity_uploads_license_command': ('troTHU.cli_teacher', 'teacher_activity_uploads_license_command'),
    'teacher_bulletins_command': ('troTHU.cli_teacher', 'teacher_bulletins_command'),
    'teacher_cancel_recommend_submission_command': ('troTHU.cli_teacher', 'teacher_cancel_recommend_submission_command'),
    'teacher_check_activity_dependents_command': ('troTHU.cli_teacher', 'teacher_check_activity_dependents_command'),
    'teacher_check_module_dependents_command': ('troTHU.cli_teacher', 'teacher_check_module_dependents_command'),
    'teacher_check_syllabus_dependents_command': ('troTHU.cli_teacher', 'teacher_check_syllabus_dependents_command'),
    'teacher_classroom_command': ('troTHU.cli_teacher', 'teacher_classroom_command'),
    'teacher_comment_exam_status_command': ('troTHU.cli_teacher', 'teacher_comment_exam_status_command'),
    'teacher_completion_criteria_command': ('troTHU.cli_teacher', 'teacher_completion_criteria_command'),
    'teacher_course_command': ('troTHU.cli_teacher', 'teacher_course_command'),
    'teacher_course_completion_criteria_command': ('troTHU.cli_teacher', 'teacher_course_completion_criteria_command'),
    'teacher_course_estimate_replies_command': ('troTHU.cli_teacher', 'teacher_course_estimate_replies_command'),
    'teacher_course_estimate_user_command': ('troTHU.cli_teacher', 'teacher_course_estimate_user_command'),
    'teacher_course_estimates_command': ('troTHU.cli_teacher', 'teacher_course_estimates_command'),
    'teacher_course_package_course_command': ('troTHU.cli_teacher', 'teacher_course_package_course_command'),
    'teacher_course_packages_command': ('troTHU.cli_teacher', 'teacher_course_packages_command'),
    'teacher_courses_command': ('troTHU.cli_teacher', 'teacher_courses_command'),
    'teacher_courseware_quizzes_command': ('troTHU.cli_teacher', 'teacher_courseware_quizzes_command'),
    'teacher_courseware_quiz_settings_command': ('troTHU.cli_teacher', 'teacher_courseware_quiz_settings_command'),
    'teacher_courseware_quiz_subjects_command': ('troTHU.cli_teacher', 'teacher_courseware_quiz_subjects_command'),
    'teacher_cc_license_groups_command': ('troTHU.cli_teacher', 'teacher_cc_license_groups_command'),
    'teacher_cc_license_map_command': ('troTHU.cli_teacher', 'teacher_cc_license_map_command'),
    'teacher_entries_command': ('troTHU.cli_teacher', 'teacher_entries_command'),
    'teacher_entry_command': ('troTHU.cli_teacher', 'teacher_entry_command'),
    'teacher_entry_references_command': ('troTHU.cli_teacher', 'teacher_entry_references_command'),
    'teacher_published_slides_command': ('troTHU.cli_teacher', 'teacher_published_slides_command'),
    'teacher_resource_group_command': ('troTHU.cli_teacher', 'teacher_resource_group_command'),
    'teacher_resource_group_folders_command': ('troTHU.cli_teacher', 'teacher_resource_group_folders_command'),
    'teacher_resource_group_members_command': ('troTHU.cli_teacher', 'teacher_resource_group_members_command'),
    'teacher_resource_group_resources_command': ('troTHU.cli_teacher', 'teacher_resource_group_resources_command'),
    'teacher_resource_group_rubrics_command': ('troTHU.cli_teacher', 'teacher_resource_group_rubrics_command'),
    'teacher_resource_group_subject_libs_command': ('troTHU.cli_teacher', 'teacher_resource_group_subject_libs_command'),
    'teacher_resource_groups_command': ('troTHU.cli_teacher', 'teacher_resource_groups_command'),
    'teacher_shared_resource_classifications_command': ('troTHU.cli_teacher', 'teacher_shared_resource_classifications_command'),
    'teacher_shared_resource_collections_command': ('troTHU.cli_teacher', 'teacher_shared_resource_collections_command'),
    'teacher_shared_resource_comments_command': ('troTHU.cli_teacher', 'teacher_shared_resource_comments_command'),
    'teacher_shared_resource_followers_command': ('troTHU.cli_teacher', 'teacher_shared_resource_followers_command'),
    'teacher_shared_resource_recommendations_command': ('troTHU.cli_teacher', 'teacher_shared_resource_recommendations_command'),
    'teacher_shared_resource_tags_command': ('troTHU.cli_teacher', 'teacher_shared_resource_tags_command'),
    'teacher_shared_resource_track_users_command': ('troTHU.cli_teacher', 'teacher_shared_resource_track_users_command'),
    'teacher_shared_resources_command': ('troTHU.cli_teacher', 'teacher_shared_resources_command'),
    'teacher_slide_command': ('troTHU.cli_teacher', 'teacher_slide_command'),
    'teacher_slide_export_status_command': ('troTHU.cli_teacher', 'teacher_slide_export_status_command'),
    'teacher_slide_records_command': ('troTHU.cli_teacher', 'teacher_slide_records_command'),
    'teacher_slides_command': ('troTHU.cli_teacher', 'teacher_slides_command'),
    'teacher_user_resource_folder_info_command': ('troTHU.cli_teacher', 'teacher_user_resource_folder_info_command'),
    'teacher_user_resources_command': ('troTHU.cli_teacher', 'teacher_user_resources_command'),
    'teacher_create_activity_command': ('troTHU.cli_teacher', 'teacher_create_activity_command'),
    'teacher_create_bulletin_command': ('troTHU.cli_teacher', 'teacher_create_bulletin_command'),
    'teacher_create_calendar_meeting_command': ('troTHU.cli_teacher', 'teacher_create_calendar_meeting_command'),
    'teacher_create_classroom_exam_command': ('troTHU.cli_teacher', 'teacher_create_classroom_exam_command'),
    'teacher_create_course_package_command': ('troTHU.cli_teacher', 'teacher_create_course_package_command'),
    'teacher_create_course_estimate_command': ('troTHU.cli_teacher', 'teacher_create_course_estimate_command'),
    'teacher_create_course_estimate_reply_command': ('troTHU.cli_teacher', 'teacher_create_course_estimate_reply_command'),
    'teacher_create_courseware_quiz_subjects_command': ('troTHU.cli_teacher', 'teacher_create_courseware_quiz_subjects_command'),
    'teacher_create_custom_score_item_command': ('troTHU.cli_teacher', 'teacher_create_custom_score_item_command'),
    'teacher_create_entry_command': ('troTHU.cli_teacher', 'teacher_create_entry_command'),
    'teacher_create_exam_command': ('troTHU.cli_teacher', 'teacher_create_exam_command'),
    'teacher_create_group_command': ('troTHU.cli_teacher', 'teacher_create_group_command'),
    'teacher_create_group_set_command': ('troTHU.cli_teacher', 'teacher_create_group_set_command'),
    'teacher_create_module_command': ('troTHU.cli_teacher', 'teacher_create_module_command'),
    'teacher_create_merged_rollcall_command': ('troTHU.cli_teacher', 'teacher_create_merged_rollcall_command'),
    'teacher_create_module_rollcall_command': ('troTHU.cli_teacher', 'teacher_create_module_rollcall_command'),
    'teacher_create_questionnaire_subject_command': ('troTHU.cli_teacher', 'teacher_create_questionnaire_subject_command'),
    'teacher_create_resource_group_command': ('troTHU.cli_teacher', 'teacher_create_resource_group_command'),
    'teacher_create_rollcall_command': ('troTHU.cli_teacher', 'teacher_create_rollcall_command'),
    'teacher_create_rubric_command': ('troTHU.cli_teacher', 'teacher_create_rubric_command'),
    'teacher_create_subject_lib_command': ('troTHU.cli_teacher', 'teacher_create_subject_lib_command'),
    'teacher_create_syllabus_command': ('troTHU.cli_teacher', 'teacher_create_syllabus_command'),
    'teacher_delete_activities_command': ('troTHU.cli_teacher', 'teacher_delete_activities_command'),
    'teacher_delete_activity_command': ('troTHU.cli_teacher', 'teacher_delete_activity_command'),
    'teacher_delete_activity_comment_command': ('troTHU.cli_teacher', 'teacher_delete_activity_comment_command'),
    'teacher_delete_activity_comment_reply_command': ('troTHU.cli_teacher', 'teacher_delete_activity_comment_reply_command'),
    'teacher_delete_activity_resource_command': ('troTHU.cli_teacher', 'teacher_delete_activity_resource_command'),
    'teacher_delete_bulletin_command': ('troTHU.cli_teacher', 'teacher_delete_bulletin_command'),
    'teacher_delete_calendar_meeting_command': ('troTHU.cli_teacher', 'teacher_delete_calendar_meeting_command'),
    'teacher_delete_classroom_command': ('troTHU.cli_teacher', 'teacher_delete_classroom_command'),
    'teacher_delete_classroom_subjects_command': ('troTHU.cli_teacher', 'teacher_delete_classroom_subjects_command'),
    'teacher_delete_course_package_command': ('troTHU.cli_teacher', 'teacher_delete_course_package_command'),
    'teacher_delete_course_estimate_command': ('troTHU.cli_teacher', 'teacher_delete_course_estimate_command'),
    'teacher_delete_course_estimate_reply_command': ('troTHU.cli_teacher', 'teacher_delete_course_estimate_reply_command'),
    'teacher_delete_custom_score_item_command': ('troTHU.cli_teacher', 'teacher_delete_custom_score_item_command'),
    'teacher_delete_entry_command': ('troTHU.cli_teacher', 'teacher_delete_entry_command'),
    'teacher_delete_exams_command': ('troTHU.cli_teacher', 'teacher_delete_exams_command'),
    'teacher_delete_group_command': ('troTHU.cli_teacher', 'teacher_delete_group_command'),
    'teacher_delete_group_member_command': ('troTHU.cli_teacher', 'teacher_delete_group_member_command'),
    'teacher_delete_group_set_command': ('troTHU.cli_teacher', 'teacher_delete_group_set_command'),
    'teacher_delete_module_command': ('troTHU.cli_teacher', 'teacher_delete_module_command'),
    'teacher_delete_questionnaire_subject_command': ('troTHU.cli_teacher', 'teacher_delete_questionnaire_subject_command'),
    'teacher_delete_resource_group_command': ('troTHU.cli_teacher', 'teacher_delete_resource_group_command'),
    'teacher_delete_resource_group_folder_command': ('troTHU.cli_teacher', 'teacher_delete_resource_group_folder_command'),
    'teacher_delete_resource_group_members_command': ('troTHU.cli_teacher', 'teacher_delete_resource_group_members_command'),
    'teacher_delete_resource_group_resource_command': ('troTHU.cli_teacher', 'teacher_delete_resource_group_resource_command'),
    'teacher_delete_rollcall_command': ('troTHU.cli_teacher', 'teacher_delete_rollcall_command'),
    'teacher_delete_rubrics_command': ('troTHU.cli_teacher', 'teacher_delete_rubrics_command'),
    'teacher_delete_shared_resource_command': ('troTHU.cli_teacher', 'teacher_delete_shared_resource_command'),
    'teacher_delete_shared_resource_comment_command': ('troTHU.cli_teacher', 'teacher_delete_shared_resource_comment_command'),
    'teacher_delete_shared_resource_to_command': ('troTHU.cli_teacher', 'teacher_delete_shared_resource_to_command'),
    'teacher_delete_slide_command': ('troTHU.cli_teacher', 'teacher_delete_slide_command'),
    'teacher_delete_slide_record_command': ('troTHU.cli_teacher', 'teacher_delete_slide_record_command'),
    'teacher_delete_subject_lib_command': ('troTHU.cli_teacher', 'teacher_delete_subject_lib_command'),
    'teacher_delete_subject_lib_subjects_command': ('troTHU.cli_teacher', 'teacher_delete_subject_lib_subjects_command'),
    'teacher_delete_syllabus_command': ('troTHU.cli_teacher', 'teacher_delete_syllabus_command'),
    'teacher_enrollments_command': ('troTHU.cli_teacher', 'teacher_enrollments_command'),
    'teacher_exam_command': ('troTHU.cli_teacher', 'teacher_exam_command'),
    'teacher_forum_categories_command': ('troTHU.cli_teacher', 'teacher_forum_categories_command'),
    'teacher_forum_category_command': ('troTHU.cli_teacher', 'teacher_forum_category_command'),
    'teacher_format_courseware_quiz_question_command': ('troTHU.cli_teacher', 'teacher_format_courseware_quiz_question_command'),
    'teacher_generate_courseware_quiz_subjects_by_text_command': ('troTHU.cli_teacher', 'teacher_generate_courseware_quiz_subjects_by_text_command'),
    'teacher_generate_courseware_quiz_subjects_command': ('troTHU.cli_teacher', 'teacher_generate_courseware_quiz_subjects_command'),
    'teacher_grade_rollcalls_command': ('troTHU.cli_teacher', 'teacher_grade_rollcalls_command'),
    'teacher_grade_submission_command': ('troTHU.cli_teacher', 'teacher_grade_submission_command'),
    'teacher_get_command': ('troTHU.cli_teacher', 'teacher_get_command'),
    'teacher_download_command': ('troTHU.cli_teacher', 'teacher_download_command'),
    'teacher_download_request_command': ('troTHU.cli_teacher', 'teacher_download_request_command'),
    'teacher_qrcode_command': ('troTHU.cli_teacher', 'teacher_qrcode_command'),
    'teacher_download_shared_resource_command': ('troTHU.cli_teacher', 'teacher_download_shared_resource_command'),
    'teacher_download_third_part_upload_command': ('troTHU.cli_teacher', 'teacher_download_third_part_upload_command'),
    'teacher_download_upload_command': ('troTHU.cli_teacher', 'teacher_download_upload_command'),
    'teacher_download_upload_modified_image_command': ('troTHU.cli_teacher', 'teacher_download_upload_modified_image_command'),
    'teacher_download_upload_reference_command': ('troTHU.cli_teacher', 'teacher_download_upload_reference_command'),
    'teacher_download_upload_swf_command': ('troTHU.cli_teacher', 'teacher_download_upload_swf_command'),
    'teacher_download_upload_thumbnail_command': ('troTHU.cli_teacher', 'teacher_download_upload_thumbnail_command'),
    'teacher_download_wedrive_file_command': ('troTHU.cli_teacher', 'teacher_download_wedrive_file_command'),
    'teacher_export_category_topics_command': ('troTHU.cli_teacher', 'teacher_export_category_topics_command'),
    'teacher_export_air_credit_command': ('troTHU.cli_teacher', 'teacher_export_air_credit_command'),
    'teacher_export_cloud_classroom_live_classes_command': ('troTHU.cli_teacher', 'teacher_export_cloud_classroom_live_classes_command'),
    'teacher_export_department_user_attendance_command': ('troTHU.cli_teacher', 'teacher_export_department_user_attendance_command'),
    'teacher_export_management_calendar_command': ('troTHU.cli_teacher', 'teacher_export_management_calendar_command'),
    'teacher_export_questionnaire_command': ('troTHU.cli_teacher', 'teacher_export_questionnaire_command'),
    'teacher_export_shared_resource_stat_command': ('troTHU.cli_teacher', 'teacher_export_shared_resource_stat_command'),
    'teacher_export_shared_resource_subject_lib_command': ('troTHU.cli_teacher', 'teacher_export_shared_resource_subject_lib_command'),
    'teacher_export_shared_resource_video_stat_command': ('troTHU.cli_teacher', 'teacher_export_shared_resource_video_stat_command'),
    'teacher_export_stat_attendance_command': ('troTHU.cli_teacher', 'teacher_export_stat_attendance_command'),
    'teacher_export_stat_courses_command': ('troTHU.cli_teacher', 'teacher_export_stat_courses_command'),
    'teacher_export_stat_report_command': ('troTHU.cli_teacher', 'teacher_export_stat_report_command'),
    'teacher_export_stat_students_command': ('troTHU.cli_teacher', 'teacher_export_stat_students_command'),
    'teacher_export_tencent_meeting_statistics_command': ('troTHU.cli_teacher', 'teacher_export_tencent_meeting_statistics_command'),
    'teacher_export_topic_command': ('troTHU.cli_teacher', 'teacher_export_topic_command'),
    'teacher_upload_file_command': ('troTHU.cli_teacher', 'teacher_upload_file_command'),
    'teacher_group_set_command': ('troTHU.cli_teacher', 'teacher_group_set_command'),
    'teacher_groups_command': ('troTHU.cli_teacher', 'teacher_groups_command'),
    'teacher_copy_group_set_command': ('troTHU.cli_teacher', 'teacher_copy_group_set_command'),
    'teacher_copy_subject_lib_command': ('troTHU.cli_teacher', 'teacher_copy_subject_lib_command'),
    'teacher_copy_subject_lib_subjects_command': ('troTHU.cli_teacher', 'teacher_copy_subject_lib_subjects_command'),
    'teacher_copy_subject_libs_to_courseware_quiz_command': ('troTHU.cli_teacher', 'teacher_copy_subject_libs_to_courseware_quiz_command'),
    'teacher_copy_subject_libs_to_user_command': ('troTHU.cli_teacher', 'teacher_copy_subject_libs_to_user_command'),
    'teacher_import_course_groups_command': ('troTHU.cli_teacher', 'teacher_import_course_groups_command'),
    'teacher_import_course_package_command': ('troTHU.cli_teacher', 'teacher_import_course_package_command'),
    'teacher_import_enrollments_command': ('troTHU.cli_teacher', 'teacher_import_enrollments_command'),
    'teacher_import_item_scores_command': ('troTHU.cli_teacher', 'teacher_import_item_scores_command'),
    'teacher_import_questionnaire_campus_subjects_command': ('troTHU.cli_teacher', 'teacher_import_questionnaire_campus_subjects_command'),
    'teacher_import_questionnaire_subjects_command': ('troTHU.cli_teacher', 'teacher_import_questionnaire_subjects_command'),
    'teacher_import_rollcalls_command': ('troTHU.cli_teacher', 'teacher_import_rollcalls_command'),
    'teacher_import_scores_command': ('troTHU.cli_teacher', 'teacher_import_scores_command'),
    'teacher_import_seat_numbers_command': ('troTHU.cli_teacher', 'teacher_import_seat_numbers_command'),
    'teacher_add_shared_resource_comment_command': ('troTHU.cli_teacher', 'teacher_add_shared_resource_comment_command'),
    'teacher_batch_delete_entries_command': ('troTHU.cli_teacher', 'teacher_batch_delete_entries_command'),
    'teacher_batch_delete_slides_command': ('troTHU.cli_teacher', 'teacher_batch_delete_slides_command'),
    'teacher_batch_save_shared_resources_command': ('troTHU.cli_teacher', 'teacher_batch_save_shared_resources_command'),
    'teacher_export_slide_command': ('troTHU.cli_teacher', 'teacher_export_slide_command'),
    'teacher_leave_resource_group_command': ('troTHU.cli_teacher', 'teacher_leave_resource_group_command'),
    'teacher_log_activity_read_command': ('troTHU.cli_teacher', 'teacher_log_activity_read_command'),
    'teacher_log_exam_activity_read_command': ('troTHU.cli_teacher', 'teacher_log_exam_activity_read_command'),
    'teacher_mark_bulletin_read_command': ('troTHU.cli_teacher', 'teacher_mark_bulletin_read_command'),
    'teacher_move_subject_lib_subjects_command': ('troTHU.cli_teacher', 'teacher_move_subject_lib_subjects_command'),
    'teacher_move_subject_libs_command': ('troTHU.cli_teacher', 'teacher_move_subject_libs_command'),
    'teacher_operate_activity_comments_command': ('troTHU.cli_teacher', 'teacher_operate_activity_comments_command'),
    'teacher_publish_activities_command': ('troTHU.cli_teacher', 'teacher_publish_activities_command'),
    'teacher_publish_shared_resource_command': ('troTHU.cli_teacher', 'teacher_publish_shared_resource_command'),
    'teacher_questionnaire_command': ('troTHU.cli_teacher', 'teacher_questionnaire_command'),
    'teacher_questionnaire_submissions_command': ('troTHU.cli_teacher', 'teacher_questionnaire_submissions_command'),
    'teacher_random_grouping_command': ('troTHU.cli_teacher', 'teacher_random_grouping_command'),
    'teacher_recommend_submissions_command': ('troTHU.cli_teacher', 'teacher_recommend_submissions_command'),
    'teacher_reply_activity_comment_command': ('troTHU.cli_teacher', 'teacher_reply_activity_comment_command'),
    'teacher_rollcall_students_command': ('troTHU.cli_teacher', 'teacher_rollcall_students_command'),
    'teacher_rollcall_info_command': ('troTHU.cli_teacher', 'teacher_rollcall_info_command'),
    'teacher_rollcall_students_page_command': ('troTHU.cli_teacher', 'teacher_rollcall_students_page_command'),
    'teacher_rollcall_count_command': ('troTHU.cli_teacher', 'teacher_rollcall_count_command'),
    'teacher_rollcall_status_result_command': ('troTHU.cli_teacher', 'teacher_rollcall_status_result_command'),
    'teacher_course_rollcall_detail_command': ('troTHU.cli_teacher', 'teacher_course_rollcall_detail_command'),
    'teacher_ongoing_student_rollcalls_command': ('troTHU.cli_teacher', 'teacher_ongoing_student_rollcalls_command'),
    'teacher_leave_record_command': ('troTHU.cli_teacher', 'teacher_leave_record_command'),
    'teacher_student_rollcalls_command': ('troTHU.cli_teacher', 'teacher_student_rollcalls_command'),
    'teacher_rollcalls_command': ('troTHU.cli_teacher', 'teacher_rollcalls_command'),
    'teacher_request_command': ('troTHU.cli_teacher', 'teacher_request_command'),
    'teacher_resort_activity_command': ('troTHU.cli_teacher', 'teacher_resort_activity_command'),
    'teacher_export_course_package_command': ('troTHU.cli_teacher', 'teacher_export_course_package_command'),
    'teacher_save_classroom_subjects_command': ('troTHU.cli_teacher', 'teacher_save_classroom_subjects_command'),
    'teacher_save_activity_resource_command': ('troTHU.cli_teacher', 'teacher_save_activity_resource_command'),
    'teacher_save_course_package_command': ('troTHU.cli_teacher', 'teacher_save_course_package_command'),
    'teacher_save_shared_resource_command': ('troTHU.cli_teacher', 'teacher_save_shared_resource_command'),
    'teacher_score_classroom_command': ('troTHU.cli_teacher', 'teacher_score_classroom_command'),
    'teacher_score_custom_item_command': ('troTHU.cli_teacher', 'teacher_score_custom_item_command'),
    'teacher_score_exam_command': ('troTHU.cli_teacher', 'teacher_score_exam_command'),
    'teacher_score_forum_command': ('troTHU.cli_teacher', 'teacher_score_forum_command'),
    'teacher_score_rollcall_command': ('troTHU.cli_teacher', 'teacher_score_rollcall_command'),
    'teacher_scores_command': ('troTHU.cli_teacher', 'teacher_scores_command'),
    'teacher_stats_command': ('troTHU.cli_teacher', 'teacher_stats_command'),
    'teacher_air_credit_command': ('troTHU.cli_teacher', 'teacher_air_credit_command'),
    'teacher_management_calendar_meetings_command': ('troTHU.cli_teacher', 'teacher_management_calendar_meetings_command'),
    'teacher_calendar_meetings_command': ('troTHU.cli_teacher', 'teacher_calendar_meetings_command'),
    'teacher_teaching_calendars_command': ('troTHU.cli_teacher', 'teacher_teaching_calendars_command'),
    'teacher_vtrses_command': ('troTHU.cli_teacher', 'teacher_vtrses_command'),
    'teacher_departments_command': ('troTHU.cli_teacher', 'teacher_departments_command'),
    'teacher_ai_ppt_command': ('troTHU.cli_teacher', 'teacher_ai_ppt_command'),
    'teacher_platform_command': ('troTHU.cli_teacher', 'teacher_platform_command'),
    'teacher_org_bulletins_command': ('troTHU.cli_teacher', 'teacher_org_bulletins_command'),
    'teacher_catalog_command': ('troTHU.cli_teacher', 'teacher_catalog_command'),
    'teacher_media_command': ('troTHU.cli_teacher', 'teacher_media_command'),
    'teacher_authoring_command': ('troTHU.cli_teacher', 'teacher_authoring_command'),
    'teacher_export_department_attendance_command': ('troTHU.cli_teacher', 'teacher_export_department_attendance_command'),
    'teacher_export_stat_vtrses_data_command': ('troTHU.cli_teacher', 'teacher_export_stat_vtrses_data_command'),
    'teacher_export_ai_ppt_usage_command': ('troTHU.cli_teacher', 'teacher_export_ai_ppt_usage_command'),
    'teacher_create_air_credit_assignments_command': ('troTHU.cli_teacher', 'teacher_create_air_credit_assignments_command'),
    'teacher_update_air_credit_assignments_command': ('troTHU.cli_teacher', 'teacher_update_air_credit_assignments_command'),
    'teacher_update_air_credit_status_command': ('troTHU.cli_teacher', 'teacher_update_air_credit_status_command'),
    'teacher_clear_air_credit_remaining_credits_command': ('troTHU.cli_teacher', 'teacher_clear_air_credit_remaining_credits_command'),
    'teacher_update_air_credit_course_usage_limit_command': ('troTHU.cli_teacher', 'teacher_update_air_credit_course_usage_limit_command'),
    'teacher_create_teaching_calendar_command': ('troTHU.cli_teacher', 'teacher_create_teaching_calendar_command'),
    'teacher_update_teaching_calendar_command': ('troTHU.cli_teacher', 'teacher_update_teaching_calendar_command'),
    'teacher_delete_teaching_calendar_command': ('troTHU.cli_teacher', 'teacher_delete_teaching_calendar_command'),
    'teacher_notify_outline_editing_command': ('troTHU.cli_teacher', 'teacher_notify_outline_editing_command'),
    'teacher_sync_courses_from_urp_command': ('troTHU.cli_teacher', 'teacher_sync_courses_from_urp_command'),
    'teacher_update_chinamcloud_resources_command': ('troTHU.cli_teacher', 'teacher_update_chinamcloud_resources_command'),
    'teacher_update_course_outline_command': ('troTHU.cli_teacher', 'teacher_update_course_outline_command'),
    'teacher_create_outline_setting_command': ('troTHU.cli_teacher', 'teacher_create_outline_setting_command'),
    'teacher_update_outline_setting_command': ('troTHU.cli_teacher', 'teacher_update_outline_setting_command'),
    'teacher_sort_outline_setting_command': ('troTHU.cli_teacher', 'teacher_sort_outline_setting_command'),
    'teacher_delete_outline_setting_option_command': ('troTHU.cli_teacher', 'teacher_delete_outline_setting_option_command'),
    'teacher_toggle_outline_setting_command': ('troTHU.cli_teacher', 'teacher_toggle_outline_setting_command'),
    'teacher_update_outline_required_options_command': ('troTHU.cli_teacher', 'teacher_update_outline_required_options_command'),
    'teacher_update_enrollment_role_command': ('troTHU.cli_teacher', 'teacher_update_enrollment_role_command'),
    'teacher_update_enrollments_role_command': ('troTHU.cli_teacher', 'teacher_update_enrollments_role_command'),
    'teacher_delete_enrollment_command': ('troTHU.cli_teacher', 'teacher_delete_enrollment_command'),
    'teacher_delete_enrollments_command': ('troTHU.cli_teacher', 'teacher_delete_enrollments_command'),
    'teacher_start_rollcall_command': ('troTHU.cli_teacher', 'teacher_start_rollcall_command'),
    'teacher_activate_rollcall_command': ('troTHU.cli_teacher', 'teacher_activate_rollcall_command'),
    'teacher_status_command': ('troTHU.cli_teacher', 'teacher_status_command'),
    'teacher_stop_rollcall_command': ('troTHU.cli_teacher', 'teacher_stop_rollcall_command'),
    'teacher_stop_timetable_rollcall_command': ('troTHU.cli_teacher', 'teacher_stop_timetable_rollcall_command'),
    'teacher_stop_qr_rollcall_command': ('troTHU.cli_teacher', 'teacher_stop_qr_rollcall_command'),
    'teacher_stop_number_rollcall_command': ('troTHU.cli_teacher', 'teacher_stop_number_rollcall_command'),
    'teacher_stop_radar_rollcall_command': ('troTHU.cli_teacher', 'teacher_stop_radar_rollcall_command'),
    'teacher_answer_qr_rollcall_command': ('troTHU.cli_teacher', 'teacher_answer_qr_rollcall_command'),
    'teacher_answer_number_rollcall_command': ('troTHU.cli_teacher', 'teacher_answer_number_rollcall_command'),
    'teacher_answer_radar_rollcall_command': ('troTHU.cli_teacher', 'teacher_answer_radar_rollcall_command'),
    'teacher_set_shared_resource_collection_command': ('troTHU.cli_teacher', 'teacher_set_shared_resource_collection_command'),
    'teacher_subject_lib_folders_command': ('troTHU.cli_teacher', 'teacher_subject_lib_folders_command'),
    'teacher_subject_lib_knowledge_nodes_command': ('troTHU.cli_teacher', 'teacher_subject_lib_knowledge_nodes_command'),
    'teacher_subject_lib_statistic_command': ('troTHU.cli_teacher', 'teacher_subject_lib_statistic_command'),
    'teacher_subject_lib_subjects_command': ('troTHU.cli_teacher', 'teacher_subject_lib_subjects_command'),
    'teacher_subject_libs_command': ('troTHU.cli_teacher', 'teacher_subject_libs_command'),
    'teacher_submit_edu_scores_command': ('troTHU.cli_teacher', 'teacher_submit_edu_scores_command'),
    'teacher_students_command': ('troTHU.cli_teacher', 'teacher_students_command'),
    'teacher_update_announce_score_settings_command': ('troTHU.cli_teacher', 'teacher_update_announce_score_settings_command'),
    'teacher_update_activity_command': ('troTHU.cli_teacher', 'teacher_update_activity_command'),
    'teacher_update_activity_comment_command': ('troTHU.cli_teacher', 'teacher_update_activity_comment_command'),
    'teacher_update_activity_comment_reply_command': ('troTHU.cli_teacher', 'teacher_update_activity_comment_reply_command'),
    'teacher_update_activity_resource_command': ('troTHU.cli_teacher', 'teacher_update_activity_resource_command'),
    'teacher_update_bulletin_command': ('troTHU.cli_teacher', 'teacher_update_bulletin_command'),
    'teacher_update_calendar_meeting_command': ('troTHU.cli_teacher', 'teacher_update_calendar_meeting_command'),
    'teacher_update_classroom_exam_command': ('troTHU.cli_teacher', 'teacher_update_classroom_exam_command'),
    'teacher_update_classroom_status_command': ('troTHU.cli_teacher', 'teacher_update_classroom_status_command'),
    'teacher_update_classroom_subject_status_command': ('troTHU.cli_teacher', 'teacher_update_classroom_subject_status_command'),
    'teacher_update_course_package_command': ('troTHU.cli_teacher', 'teacher_update_course_package_command'),
    'teacher_update_courseware_quiz_subjects_command': ('troTHU.cli_teacher', 'teacher_update_courseware_quiz_subjects_command'),
    'teacher_update_course_estimate_command': ('troTHU.cli_teacher', 'teacher_update_course_estimate_command'),
    'teacher_update_custom_score_item_command': ('troTHU.cli_teacher', 'teacher_update_custom_score_item_command'),
    'teacher_update_enrollment_scores_command': ('troTHU.cli_teacher', 'teacher_update_enrollment_scores_command'),
    'teacher_update_entry_command': ('troTHU.cli_teacher', 'teacher_update_entry_command'),
    'teacher_update_exam_command': ('troTHU.cli_teacher', 'teacher_update_exam_command'),
    'teacher_update_forum_status_command': ('troTHU.cli_teacher', 'teacher_update_forum_status_command'),
    'teacher_sort_groups_command': ('troTHU.cli_teacher', 'teacher_sort_groups_command'),
    'teacher_sort_module_activities_command': ('troTHU.cli_teacher', 'teacher_sort_module_activities_command'),
    'teacher_sort_modules_command': ('troTHU.cli_teacher', 'teacher_sort_modules_command'),
    'teacher_sort_syllabus_activities_command': ('troTHU.cli_teacher', 'teacher_sort_syllabus_activities_command'),
    'teacher_sort_syllabuses_command': ('troTHU.cli_teacher', 'teacher_sort_syllabuses_command'),
    'teacher_update_group_command': ('troTHU.cli_teacher', 'teacher_update_group_command'),
    'teacher_update_group_info_command': ('troTHU.cli_teacher', 'teacher_update_group_info_command'),
    'teacher_update_group_member_command': ('troTHU.cli_teacher', 'teacher_update_group_member_command'),
    'teacher_update_group_members_command': ('troTHU.cli_teacher', 'teacher_update_group_members_command'),
    'teacher_update_group_set_command': ('troTHU.cli_teacher', 'teacher_update_group_set_command'),
    'teacher_update_homework_announce_status_command': ('troTHU.cli_teacher', 'teacher_update_homework_announce_status_command'),
    'teacher_update_homework_rubric_command': ('troTHU.cli_teacher', 'teacher_update_homework_rubric_command'),
    'teacher_update_module_command': ('troTHU.cli_teacher', 'teacher_update_module_command'),
    'teacher_update_merged_rollcall_students_command': ('troTHU.cli_teacher', 'teacher_update_merged_rollcall_students_command'),
    'teacher_update_rollcall_command': ('troTHU.cli_teacher', 'teacher_update_rollcall_command'),
    'teacher_update_radar_rollcall_position_command': ('troTHU.cli_teacher', 'teacher_update_radar_rollcall_position_command'),
    'teacher_update_student_rollcalls_command': ('troTHU.cli_teacher', 'teacher_update_student_rollcalls_command'),
    'teacher_update_questionnaire_subject_command': ('troTHU.cli_teacher', 'teacher_update_questionnaire_subject_command'),
    'teacher_update_resource_group_command': ('troTHU.cli_teacher', 'teacher_update_resource_group_command'),
    'teacher_update_resource_group_resource_command': ('troTHU.cli_teacher', 'teacher_update_resource_group_resource_command'),
    'teacher_update_rubric_command': ('troTHU.cli_teacher', 'teacher_update_rubric_command'),
    'teacher_update_score_book_command': ('troTHU.cli_teacher', 'teacher_update_score_book_command'),
    'teacher_update_score_publish_item_maps_command': ('troTHU.cli_teacher', 'teacher_update_score_publish_item_maps_command'),
    'teacher_update_score_type_settings_command': ('troTHU.cli_teacher', 'teacher_update_score_type_settings_command'),
    'teacher_update_slide_command': ('troTHU.cli_teacher', 'teacher_update_slide_command'),
    'teacher_update_slide_video_info_command': ('troTHU.cli_teacher', 'teacher_update_slide_video_info_command'),
    'teacher_update_subject_lib_command': ('troTHU.cli_teacher', 'teacher_update_subject_lib_command'),
    'teacher_update_syllabus_command': ('troTHU.cli_teacher', 'teacher_update_syllabus_command'),
    'teacher_update_total_scores_command': ('troTHU.cli_teacher', 'teacher_update_total_scores_command'),
    'teacher_update_rollcall_setting_command': ('troTHU.cli_teacher', 'teacher_update_rollcall_setting_command'),
    'teacher_unset_shared_resource_collection_command': ('troTHU.cli_teacher', 'teacher_unset_shared_resource_collection_command'),
    'tronclass_api_endpoints': ('troTHU.providers', 'tronclass_api_endpoints'),
    'unbind_account': ('troTHU.cli_accounts', 'unbind_account'),
    'validate_login_api_session': ('troTHU.auth_runtime', 'validate_login_api_session'),
    'validation_checklist_command': ('troTHU.cli_system', 'validation_checklist_command'),
    'validation_local_smoke_command': ('troTHU.cli_system', 'validation_local_smoke_command'),
    'validation_record_command': ('troTHU.cli_system', 'validation_record_command'),
    'validation_summary_command': ('troTHU.cli_system', 'validation_summary_command'),
    'webview_import_command': ('troTHU.cli_app', 'webview_import_command'),
    'webview_preview_command': ('troTHU.cli_app', 'webview_preview_command'),
    'webview_status_command': ('troTHU.cli_app', 'webview_status_command'),
    'write_config_file': ('troTHU.config_runtime', 'write_config_file'),
    'write_advanced_config_file': ('troTHU.config_runtime', 'write_advanced_config_file'),
    'write_compact_config': ('troTHU.config_view', 'write_compact_config'),
}

def __getattr__(name: str):
    if name in _LEGACY_EXPORTS:
        module_name, attr_name = _LEGACY_EXPORTS[name]
        try:
            module = importlib.import_module(module_name)
        except ImportError:  # pragma: no cover - direct script fallback
            module = importlib.import_module(module_name.removeprefix("troTHU."))
        value = getattr(module, attr_name)
        globals()[name] = value
        return value
    raise AttributeError(name)

def __dir__():
    return sorted(set(globals()) | set(_LEGACY_EXPORTS))

CONFIG = copy.deepcopy(DEFAULT_CONFIG)
NOTIFICATION_SINKS = []
IS_LOGGING_IN = False
cnt = 0
